### ISSUE TITLE
Typo in the documentation of TargetEncoder

### ISSUE THREAD

**Issue by janmotl** [scikit-learn-contrib/categorical-encoding#107]
Typo: TargetEncode -> TargetEncoder

**Comment by wdm0006** [comment]
Hey @janmotl, I've invited you to the org as a maintainer, please continue to make PRs for any significant features (typos are fine to commit directly). I'm traveling quite a bit right now, but will check in here when I can.

**Comment by janmotl** [comment]
Solved with #110
