### ISSUE TITLE
The fit method of TargetEncoder does not pass smoothing_in

### ISSUE THREAD

**Issue by JohnnyC08** [scikit-learn-contrib/categorical-encoding#109]
In the TargetEncoder the fit method does not pass smoothing_in into target_encode which causes the method to default to 1 for smoothing. Also, when we check transform we see that the smoothing_in is passed as the self.smoothing, but if we are calling transform after fit, then we don't even use smoothing_in since the mapping is already set.

I can submit a PR which sets the parameter and add a test to https://github.com/scikit-learn-contrib/categorical-encoding/blob/master/category_encoders/tests/test_encoders.py . Before I do so, I want to confirm this is indeed an issue.

**Comment by janmotl** [comment]
Both issues are valid. When we are performing the fitting, we should use`self.smoothing`. When we are transforming, we only need `mapping` - there is no need for `self.smoothing`.

PR with tests sounds great.

**Comment by JohnnyC08** [comment]
Closing as the fix was merged in
