### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by discdiver** [scikit-learn-contrib/categorical-encoding#115]
Great package! Working on an article of Category Encoder's methods. Last release was 8 months ago - looks like quite few fixes and enhancements since then. Is a new release in the offing?

**Comment by wdm0006** [comment]
Hey @discdiver, thanks! I've been a bit out of the loop recently, my company got acquired so I've been traveling a lot (thanks to @janmotl for the help along the way). I need to carve out some time to bucket some issues into releases and cut a release for sure, we are long overdue. Will try to over the holiday.

**Comment by wdm0006** [comment]
So I've gone through some of the issues in the backlog and tagged those that are good candidates for a v1.3.0 release, many of which @janmotl has addressed in #110. 

There are a handful of bugs that I think probably should also be resolved before a release:

 * #86 
 * #91 
 * #100 
 * #105 
 * #106 

But the nature of some of them leads me to think that they will be easier to address once #110 is merged in, which ought to be soon, I've reviewed it and it looked quite good. 

So release is probably not this weekend, but we are tracking it now under the v1.3.0 milestone, and welcome anyone to help grab any of those 5 open bugs above and work towards it.

**Comment by janmotl** [comment]
@wdm0006 Can we do the release before #86? Reasoning: users have difficulties to install this library (#123, #130) and new release would solve it.

**Comment by wdm0006** [comment]
Yeah, I think that makes sense. I'll do a minor release today.

**Comment by wdm0006** [comment]
done, v1.3.0 out on pypi
