### ISSUE TITLE
HashingEncoder does not accept handle_unknown argument

### ISSUE THREAD

**Issue by janmotl** [scikit-learn-contrib/categorical-encoding#120]
Can HashingEncoder accept new values (values that are not observed in the training set) in the testing dataset?

If yes, it should possibly be noted in the documentation of the encoder.

**Comment by wdm0006** [comment]
Yes, it can. Agreed on documentation, it behaves differently than many of the other encoders in that it does not maintain a dictionary of potential categories, you can throw whatever you want at it.

**Comment by janmotl** [comment]
Documentation extended with https://github.com/scikit-learn-contrib/categorical-encoding/commit/b418a2a44a65c4097378c582416f009df5e61ea3
