### ISSUE TITLE
inverse_transform() in BaseNEncoder does not raise an exception  

### ISSUE THREAD

**Issue by janmotl** [scikit-learn-contrib/categorical-encoding#121]
inverse_transform() in BaseNEncoder does not raise an exception when the test set contains a new value:

```python
        X = create_dataset(n_rows=100, has_none=False)
        X_t = create_dataset(n_rows=50, has_none=False)
        X_t_extra = create_dataset(n_rows=50, extras=True, has_none=False)
        cols = ['underscore', 'none', 'extra', 321]

         enc = category_encoders.BaseNEncoder(verbose=1, cols=cols)
         enc.fit(X, y)
         with self.assertRaises(ValueError):
                _ = enc.inverse_transform(enc.transform(X_t_extra))
```

**Comment by janmotl** [comment]
It looks like an error could be in the remaining encoders. OneHot, Binary and Ordinal use following code:
```python
for col in self.cols:
    if any(X[col] == 0):
        raise ValueError("inverse_transform is not supported because transform impute "
                                     "the unknown category -1 when encode %s"%(col,))
```
While BaseN uses:
```python
for col in self.cols:
    if any(X[col] == -1):
        raise ValueError("inverse_transform is not supported because transform impute "
                                     "the unknown category -1 when encode %s"%(col,))
```
Note the difference between `X[col] == 0` and `X[col] == -1`.

My hypothesis is that there should be -1 everywhere. 0 is merely a historical artifact from the time when 0 used to be used to mark unknown categories. Am I right?

**Comment by wdm0006** [comment]
Ah yes, should be -1 everywhere, 0 is legacy and causes issues. Should switch it to -1.

**Comment by janmotl** [comment]
Resolved with commit https://github.com/scikit-learn-contrib/categorical-encoding/commit/037c7cdcbe133dcfea5f23809f74b903c599d457
