### ISSUE TITLE
Does TargetEncoder really implement leave one out approach as it's stated in the docs?

### ISSUE THREAD

**Issue by deil87** [scikit-learn-contrib/categorical-encoding#124]
"Target Encode for categorical features. Based on **leave one out** approach." - that is what [documentation](http://contrib.scikit-learn.org/categorical-encoding/targetencoder.html#category_encoders.target_encoder.TargetEncoder) says.

I know that published documentation does not represent the last version of the code and that is why I've taken a look at the sources on github. I have not found any logic that uses Y/target column and subtract during application phase current row's values from aggregated per category values. 

Could anyone please clarify? If it is not a bug than could you please point out( give a reference) to what leave one out means in this context?

**Comment by janmotl** [comment]
The documentation is misleading - the sentence refers to the fact that the implementation was done by modifying the code of LeaveOneOutEncoder. Nothing else.

I suggest to replace the description of the method with:
```
Target Encode for categorical features. Categorical features are replaced with a blend
of the average of the target over all the training data and the average of the target over
training samples taking the given categorical value.
```
But better descriptions are welcomed.

**Comment by janmotl** [comment]
That reads better. However, target encoder also works on regression problems...

**Comment by deil87** [comment]
Yes it works. I don't see how we can squeeze in two things( expected value and probability) in one. But I think since expected value depends on the probability of the single event and continuous case could be seen as multi-categorical case.... we can probably use probability? wdyt? Or we can write down separate sentence  for each of the case.

**Comment by janmotl** [comment]
Will you write the separate sentences?

**Comment by janmotl** [comment]
Thank you!
