### ISSUE TITLE
Difference in statsmodels dependencies in git vs pypi.

### ISSUE THREAD

**Issue by brandonmichaelgarcia** [scikit-learn-contrib/categorical-encoding#130]
It seems that the git repo reports that there is a dependency on statsmodels >=0.6.0. However, the pip install has the requirement of statsmodels <= 0.8.0 and >=0.6.0. Removing the upper limit on the statsmodels dependency allows for simple install for python 3.7 development. Perhaps this is already on the to-do list?

**Comment by janmotl** [comment]
We aim to publish a new release (#115) that will be without the upper cap.

**Comment by wdm0006** [comment]
v1.3.0 released
