### ISSUE TITLE
Update release version to 1.3.0 on GitHub

### ISSUE THREAD

**Issue by discdiver** [scikit-learn-contrib/categorical-encoding#138]
Showing 1.2.6 on GitHub.

**Comment by janmotl** [comment]
@wdm0006 Shouldn't this be handled by:
```
 Release automatically generated by pypi-publisher 
```
?

**Comment by wdm0006** [comment]
Yeah, pypi-publisher stopped working with the new pypi at some point, so the recent couple of releases have been w/ twine. Current version on pypi is v1.3.0, working on v1.4.0 now. When we do the v1.4.0 release, I'll update pypi-publisher to make sure it shows up on github as well.
