### ISSUE TITLE
one hot encoder handle unknown

### ISSUE THREAD

**Issue by geoHeil** [scikit-learn-contrib/categorical-encoding#14]
Sklearn offers the "handle unknown flag" http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html with either rise error or ignore.

Do you have any plans to support this? / add a 3rd Option of creating a new category call unknown.

**Comment by wdm0006** [comment]
That's a good thought. 

I think it would make sense to support what you're suggesting here:

 1. ignore: so if something new shows up, just do nothing
 2. raise: raise a valueerror
 3. keep_unknown (or something like that), would have an unknown column that gets a 1 for any unseen categories. 

I'm not sure what the most sensible default would be, maybe ignore?

**Comment by geoHeil** [comment]
Sklearn is using raise error. I believe this is the most sensible default,
as the user will be forced to decide.

Will McGinnis <notifications@github.com> schrieb am Sa., 8. Okt. 2016 um
21:30 Uhr:

**Comment by wdm0006** [comment]
That makes sense, are you interesting in working on this? I likely won't have time for the next few weeks.

**Comment by geoHeil** [comment]
Unfortunately me neither. ;(

Will McGinnis <notifications@github.com> schrieb am Di., 11. Okt. 2016 um
16:55 Uhr:

**Comment by wdm0006** [comment]
Ok, looking at this again, I'd like to keep the existing method of `impute_missing` around for a little while to not break existing users' code. 

To handle that transition, we could leave `impute_missing` as a boolean, and if it's true (it defaults to True currently), then apply the logic specified by a new parameter `handle_unknown` which has options 'error', 'ignore' and 'impute_unknown', defaulting to 'impute_known'. 

That way for the next release or two, current default behavior will remain, and we can raise a deprecation warning for `impute_missing` to remove it later.  

That make sense to you?

**Comment by a86c6f7964** [comment]
@wdm0006 can you do a pip release with this fix?

**Comment by DataTerminatorX** [comment]
I have the same suggestion as @geoHeil . While I think the best way to handle unseen categorical value is to set all zeros, like pandas `get_dummies`. Adding a new column called `unknown` is not proper, because this column will be "redundant" dimension

@wdm0006  hope for a release with this new feature. The issue hasn't been fixed in current sklearn version `0.19.1`
