### ISSUE TITLE
Unalignable boolean Series Error

### ISSUE THREAD

**Issue by christopherbuhtz** [scikit-learn-contrib/categorical-encoding#151]
After the update to category_encoders version 1.3.0 we encountered the following error when working with subsets of DataFrames.

```python
d = {'categorical_var': ['A', 'B','C','A','B'], 'y': [3, 4, 5, 7, 3]}
train = pd.DataFrame(data=d)
train = train.iloc[2:5]

target_enc = TargetEncoder(verbose=True).fit(X=train, y=train.y)

target_enc.transform(train)
```

```python
---------------------------------------------------------------------------
IndexingError                             Traceback (most recent call last)
<ipython-input-63-89aa76133915> in <module>()
      1 target_enc = TargetEncoder(verbose=True).fit(X=train,y=train.erfolgreich)
      2 
----> 3 target_enc.transform(train)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\category_encoders\target_encoder.py in transform(self, X, y)
    183             handle_unknown=self.handle_unknown,
    184             min_samples_leaf=self.min_samples_leaf,
--> 185             smoothing_in=self.smoothing
    186         )
    187 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\category_encoders\target_encoder.py in target_encode(self, X_in, y, mapping, cols, impute_missing, handle_unknown, min_samples_leaf, smoothing_in)
    216                 for val in switch.get('mapping'):
    217                     if switch.get('mapping')[val]['count'] == 1:
--> 218                         transformed_column.loc[X[column] == val] = self._mean
    219                     else:
    220                         transformed_column.loc[X[column] == val] = switch.get('mapping')[val]['smoothing']

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py in __setitem__(self, key, value)
    186         else:
    187             key = com._apply_if_callable(key, self.obj)
--> 188         indexer = self._get_setitem_indexer(key)
    189         self._setitem_with_indexer(indexer, value)
    190 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py in _get_setitem_indexer(self, key)
    172 
    173         try:
--> 174             return self._convert_to_indexer(key, is_setter=True)
    175         except TypeError as e:
    176 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py in _convert_to_indexer(self, obj, axis, is_setter)
   1298 
   1299             if com.is_bool_indexer(obj):
-> 1300                 obj = check_bool_indexer(labels, obj)
   1301                 inds, = obj.nonzero()
   1302                 return inds

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py in check_bool_indexer(ax, key)
   2354         mask = isna(result._values)
   2355         if mask.any():
-> 2356             raise IndexingError('Unalignable boolean Series provided as '
   2357                                 'indexer (index of the boolean Series and of '
   2358                                 'the indexed object do not match')

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match

```
The error is only thrown after transform, the fitting part works fine. If instead I write:
```
target_enc.transform(train.reset_index(drop=True))
```
...it works again. We encountered this behavior when splitting the data into training and test sets. The fitting on the training data worked but transforming the test data did not. Is this behaviour expected?

**Comment by janmotl** [comment]
Yes, not all encoders in release 1.3.0 work with noncontinuous indexes. Nevertheless, all encoders in the current development version are tested to work with noncontinuous indexes.

Download the development version. If it solves the problem, you may close the issue.

**Comment by WeihaoZeng** [comment]
I have a same error when I used TargetEncoder in sklearn pipeline.

**Comment by nikwerhypoport** [comment]
> I have a same error when I used TargetEncoder in sklearn pipeline.

Hey, we solved this by forking the dev branch of the project and doing our own release. 
Despite the mentioned error, the version 1.3.0 has severe performance issues, which seem to be fixed in the development version as well.
Maybe we can close the issue, when a new official release is out.

**Comment by janmotl** [comment]
@nikwerhypoport Thank you for the report. The current development version indeed has 2 advantages in comparison to the version 1.3.0:
1. Some of the encoders were vectorized (Ordinal, LeaveOneOut, OneHot, TargetEncoder, WOE). That delivered significant speed up.
2. All encoders are tested to work with noncontinuous indexes.

Furthermore, there is an undergoing work to document and improve handling of missing values and handling of new values observed during the scoring. The plan is that once that will be done (the date is not fixed), a new release will be published and this issue will be closed.

**Comment by wdm0006** [comment]
This should be in v1.4.0, a release being worked on now, closing this issue.

**Comment by gitwhistle** [comment]
> Yes, not all encoders in release 1.3.0 work with noncontinuous indexes (even if you just trim indexes from the left). Nevertheless, all encoders in the current development version are tested to work with noncontinuous indexes.
> 
> Download the development version. If it solves the problem, you may close the issue.

How do I download the development version?

**Comment by janmotl** [comment]
For me, following works:
```bash
pip3 install --upgrade git+https://github.com/scikit-learn-contrib/categorical-encoding
```
