### ISSUE TITLE
OneHotEncoder value error when all categories are unseen for handle_unknown='ignore'

### ISSUE THREAD

**Issue by joshuahyatt** [scikit-learn-contrib/categorical-encoding#154]
<body>
  <div tabindex="-1" id="notebook" class="border-box-sizing">
    <div class="container" id="notebook-container">

<div class="cell border-box-sizing code_cell rendered">
<div class="input">
<div class="prompt input_prompt">In&nbsp;[1]:</div>
<div class="inner_cell">
    <div class="input_area">
<div class=" highlight hl-ipython3"><pre><span></span><span class="kn">from</span> <span class="nn">category_encoders</span> <span class="k">import</span> <span class="n">OneHotEncoder</span>
<span class="kn">import</span> <span class="nn">numpy</span> <span class="k">as</span> <span class="nn">np</span>
<span class="kn">import</span> <span class="nn">pandas</span> <span class="k">as</span> <span class="nn">pd</span>
</pre></div>

</div>
</div>
</div>

</div>
<div class="cell border-box-sizing text_cell rendered"><div class="prompt input_prompt">
</div>
<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<h3 id="OneHotEncoder-behaves-as-expected-when-some-categories-are-known">OneHotEncoder behaves as expected when some categories are known<a class="anchor-link" href="#OneHotEncoder-behaves-as-expected-when-some-categories-are-known">&#182;</a></h3>
</div>
</div>
</div>
<div class="cell border-box-sizing code_cell rendered">
<div class="input">
<div class="prompt input_prompt">In&nbsp;[2]:</div>
<div class="inner_cell">
    <div class="input_area">
<div class=" highlight hl-ipython3"><pre><span></span><span class="n">train</span> <span class="o">=</span> <span class="p">{</span><span class="s1">&#39;city&#39;</span><span class="p">:</span> <span class="p">[</span><span class="s1">&#39;Buenos Aires&#39;</span><span class="p">,</span> <span class="s1">&#39;New York&#39;</span><span class="p">,</span> <span class="s1">&#39;Istambul&#39;</span><span class="p">,</span> <span class="s1">&#39;Buenos Aires&#39;</span><span class="p">,</span> <span class="s1">&#39;Paris&#39;</span><span class="p">,</span> <span class="s1">&#39;Paris&#39;</span><span class="p">]}</span>
<span class="n">train</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">train</span><span class="p">)</span>

<span class="n">test</span> <span class="o">=</span> <span class="p">{</span><span class="s1">&#39;city&#39;</span><span class="p">:</span> <span class="p">[</span><span class="s1">&#39;Buenos Aires&#39;</span><span class="p">,</span> <span class="s1">&#39;New York&#39;</span><span class="p">,</span> <span class="s1">&#39;Istambul&#39;</span><span class="p">,</span> <span class="s1">&#39;Buenos Aires&#39;</span><span class="p">,</span> <span class="s1">&#39;Paris&#39;</span><span class="p">,</span> <span class="s1">&#39;Utila&#39;</span><span class="p">]}</span>
<span class="n">test</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">test</span><span class="p">)</span>
</pre></div>

</div>
</div>
</div>

</div>
<div class="cell border-box-sizing code_cell rendered">
<div class="input">
<div class="prompt input_prompt">In&nbsp;[18]:</div>
<div class="inner_cell">
    <div class="input_area">
<div class=" highlight hl-ipython3"><pre><span></span><span class="n">encoder</span> <span class="o">=</span> <span class="n">OneHotEncoder</span><span class="p">(</span><span class="n">handle_unknown</span><span class="o">=</span><span class="s1">&#39;ignore&#39;</span><span class="p">)</span><span class="o">.</span><span class="n">fit</span><span class="p">(</span><span class="n">train</span><span class="p">)</span>
</pre></div>

</div>
</div>
</div>

</div>
<div class="cell border-box-sizing code_cell rendered">
<div class="input">
<div class="prompt input_prompt">In&nbsp;[19]:</div>
<div class="inner_cell">
    <div class="input_area">
<div class=" highlight hl-ipython3"><pre><span></span><span class="n">encoder</span><span class="o">.</span><span class="n">transform</span><span class="p">(</span><span class="n">test</span><span class="p">)</span>
</pre></div>

</div>
</div>
</div>

<div class="output_wrapper">
<div class="output">

<div class="output_area">

<div class="prompt output_prompt">Out[19]:</div>

<div class="output_html rendered_html output_subarea output_execute_result">
<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>city_1</th>
      <th>city_2</th>
      <th>city_3</th>
      <th>city_4</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
</div>
</div>

</div>

</div>
</div>

</div>
<div class="cell border-box-sizing text_cell rendered"><div class="prompt input_prompt">
</div>
<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<h3 id="It-fails-However-when-all-categories-are-unkown">It fails However when all categories are unkown<a class="anchor-link" href="#It-fails-However-when-all-categories-are-unkown">&#182;</a></h3>
</div>
</div>
</div>
<div class="cell border-box-sizing code_cell rendered">
<div class="input">
<div class="prompt input_prompt">In&nbsp;[20]:</div>
<div class="inner_cell">
    <div class="input_area">
<div class=" highlight hl-ipython3"><pre><span></span><span class="n">test_none</span> <span class="o">=</span> <span class="p">{</span><span class="s1">&#39;city&#39;</span><span class="p">:</span> <span class="p">[</span><span class="s1">&#39;Chicago&#39;</span><span class="p">,</span> <span class="s1">&#39;London&#39;</span><span class="p">,</span> <span class="s1">&#39;Stockholm&#39;</span><span class="p">,</span> <span class="s1">&#39;Utila&#39;</span><span class="p">]}</span>
<span class="n">test_none</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">test_none</span><span class="p">)</span>
</pre></div>

</div>
</div>
</div>

</div>
<div class="cell border-box-sizing code_cell rendered">
<div class="input">
<div class="prompt input_prompt">In&nbsp;[21]:</div>
<div class="inner_cell">
    <div class="input_area">
<div class=" highlight hl-ipython3"><pre><span></span><span class="n">encoder</span><span class="o">.</span><span class="n">transform</span><span class="p">(</span><span class="n">test_none</span><span class="p">)</span>
</pre></div>

</div>
</div>
</div>

<div class="output_wrapper">
<div class="output">

<div class="output_area">

<div class="prompt"></div>

<div class="output_subarea output_text output_error">
<pre>
<span class="ansi-red-intense-fg ansi-bold">---------------------------------------------------------------------------</span>
<span class="ansi-red-intense-fg ansi-bold">TypeError</span>                                 Traceback (most recent call last)
<span class="ansi-green-intense-fg ansi-bold">&lt;ipython-input-21-f21616b9124f&gt;</span> in <span class="ansi-cyan-fg">&lt;module&gt;</span><span class="ansi-blue-intense-fg ansi-bold">()</span>
<span class="ansi-green-intense-fg ansi-bold">----&gt; 1</span><span class="ansi-yellow-intense-fg ansi-bold"> </span>encoder<span class="ansi-yellow-intense-fg ansi-bold">.</span>transform<span class="ansi-yellow-intense-fg ansi-bold">(</span>test_none<span class="ansi-yellow-intense-fg ansi-bold">)</span>

<span class="ansi-green-intense-fg ansi-bold">C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\category_encoders\one_hot.py</span> in <span class="ansi-cyan-fg">transform</span><span class="ansi-blue-intense-fg ansi-bold">(self, X)</span>
<span class="ansi-green-fg">    175</span>             <span class="ansi-green-intense-fg ansi-bold">return</span> X <span class="ansi-green-intense-fg ansi-bold">if</span> self<span class="ansi-yellow-intense-fg ansi-bold">.</span>return_df <span class="ansi-green-intense-fg ansi-bold">else</span> X<span class="ansi-yellow-intense-fg ansi-bold">.</span>values
<span class="ansi-green-fg">    176</span> 
<span class="ansi-green-intense-fg ansi-bold">--&gt; 177</span><span class="ansi-yellow-intense-fg ansi-bold">         </span>X <span class="ansi-yellow-intense-fg ansi-bold">=</span> self<span class="ansi-yellow-intense-fg ansi-bold">.</span>ordinal_encoder<span class="ansi-yellow-intense-fg ansi-bold">.</span>transform<span class="ansi-yellow-intense-fg ansi-bold">(</span>X<span class="ansi-yellow-intense-fg ansi-bold">)</span>
<span class="ansi-green-fg">    178</span> 
<span class="ansi-green-fg">    179</span>         X <span class="ansi-yellow-intense-fg ansi-bold">=</span> self<span class="ansi-yellow-intense-fg ansi-bold">.</span>get_dummies<span class="ansi-yellow-intense-fg ansi-bold">(</span>X<span class="ansi-yellow-intense-fg ansi-bold">,</span> cols<span class="ansi-yellow-intense-fg ansi-bold">=</span>self<span class="ansi-yellow-intense-fg ansi-bold">.</span>cols<span class="ansi-yellow-intense-fg ansi-bold">)</span>

<span class="ansi-green-intense-fg ansi-bold">C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\category_encoders\ordinal.py</span> in <span class="ansi-cyan-fg">transform</span><span class="ansi-blue-intense-fg ansi-bold">(self, X)</span>
<span class="ansi-green-fg">    179</span>             cols<span class="ansi-yellow-intense-fg ansi-bold">=</span>self<span class="ansi-yellow-intense-fg ansi-bold">.</span>cols<span class="ansi-yellow-intense-fg ansi-bold">,</span>
<span class="ansi-green-fg">    180</span>             impute_missing<span class="ansi-yellow-intense-fg ansi-bold">=</span>self<span class="ansi-yellow-intense-fg ansi-bold">.</span>impute_missing<span class="ansi-yellow-intense-fg ansi-bold">,</span>
<span class="ansi-green-intense-fg ansi-bold">--&gt; 181</span><span class="ansi-yellow-intense-fg ansi-bold">             </span>handle_unknown<span class="ansi-yellow-intense-fg ansi-bold">=</span>self<span class="ansi-yellow-intense-fg ansi-bold">.</span>handle_unknown
<span class="ansi-green-fg">    182</span>         )
<span class="ansi-green-fg">    183</span> 

<span class="ansi-green-intense-fg ansi-bold">C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\category_encoders\ordinal.py</span> in <span class="ansi-cyan-fg">ordinal_encoding</span><span class="ansi-blue-intense-fg ansi-bold">(X_in, mapping, cols, impute_missing, handle_unknown)</span>
<span class="ansi-green-fg">    261</span> 
<span class="ansi-green-fg">    262</span>                 <span class="ansi-green-intense-fg ansi-bold">try</span><span class="ansi-yellow-intense-fg ansi-bold">:</span>
<span class="ansi-green-intense-fg ansi-bold">--&gt; 263</span><span class="ansi-yellow-intense-fg ansi-bold">                     </span>X<span class="ansi-yellow-intense-fg ansi-bold">[</span>switch<span class="ansi-yellow-intense-fg ansi-bold">.</span>get<span class="ansi-yellow-intense-fg ansi-bold">(</span><span class="ansi-blue-intense-fg ansi-bold">&#39;col&#39;</span><span class="ansi-yellow-intense-fg ansi-bold">)</span><span class="ansi-yellow-intense-fg ansi-bold">]</span> <span class="ansi-yellow-intense-fg ansi-bold">=</span> X<span class="ansi-yellow-intense-fg ansi-bold">[</span>switch<span class="ansi-yellow-intense-fg ansi-bold">.</span>get<span class="ansi-yellow-intense-fg ansi-bold">(</span><span class="ansi-blue-intense-fg ansi-bold">&#39;col&#39;</span><span class="ansi-yellow-intense-fg ansi-bold">)</span><span class="ansi-yellow-intense-fg ansi-bold">]</span><span class="ansi-yellow-intense-fg ansi-bold">.</span>astype<span class="ansi-yellow-intense-fg ansi-bold">(</span>int<span class="ansi-yellow-intense-fg ansi-bold">)</span><span class="ansi-yellow-intense-fg ansi-bold">.</span>values<span class="ansi-yellow-intense-fg ansi-bold">.</span>reshape<span class="ansi-yellow-intense-fg ansi-bold">(</span><span class="ansi-yellow-intense-fg ansi-bold">-</span><span class="ansi-cyan-intense-fg ansi-bold">1</span><span class="ansi-yellow-intense-fg ansi-bold">,</span> <span class="ansi-yellow-intense-fg ansi-bold">)</span>
<span class="ansi-green-fg">    264</span>                 <span class="ansi-green-intense-fg ansi-bold">except</span> ValueError <span class="ansi-green-intense-fg ansi-bold">as</span> e<span class="ansi-yellow-intense-fg ansi-bold">:</span>
<span class="ansi-green-fg">    265</span>                     X<span class="ansi-yellow-intense-fg ansi-bold">[</span>switch<span class="ansi-yellow-intense-fg ansi-bold">.</span>get<span class="ansi-yellow-intense-fg ansi-bold">(</span><span class="ansi-blue-intense-fg ansi-bold">&#39;col&#39;</span><span class="ansi-yellow-intense-fg ansi-bold">)</span><span class="ansi-yellow-intense-fg ansi-bold">]</span> <span class="ansi-yellow-intense-fg ansi-bold">=</span> X<span class="ansi-yellow-intense-fg ansi-bold">[</span>switch<span class="ansi-yellow-intense-fg ansi-bold">.</span>get<span class="ansi-yellow-intense-fg ansi-bold">(</span><span class="ansi-blue-intense-fg ansi-bold">&#39;col&#39;</span><span class="ansi-yellow-intense-fg ansi-bold">)</span><span class="ansi-yellow-intense-fg ansi-bold">]</span><span class="ansi-yellow-intense-fg ansi-bold">.</span>astype<span class="ansi-yellow-intense-fg ansi-bold">(</span>float<span class="ansi-yellow-intense-fg ansi-bold">)</span><span class="ansi-yellow-intense-fg ansi-bold">.</span>values<span class="ansi-yellow-intense-fg ansi-bold">.</span>reshape<span class="ansi-yellow-intense-fg ansi-bold">(</span><span class="ansi-yellow-intense-fg ansi-bold">-</span><span class="ansi-cyan-intense-fg ansi-bold">1</span><span class="ansi-yellow-intense-fg ansi-bold">,</span> <span class="ansi-yellow-intense-fg ansi-bold">)</span>

<span class="ansi-green-intense-fg ansi-bold">C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\pandas\util\_decorators.py</span> in <span class="ansi-cyan-fg">wrapper</span><span class="ansi-blue-intense-fg ansi-bold">(*args, **kwargs)</span>
<span class="ansi-green-fg">     89</span>                 <span class="ansi-green-intense-fg ansi-bold">else</span><span class="ansi-yellow-intense-fg ansi-bold">:</span>
<span class="ansi-green-fg">     90</span>                     kwargs<span class="ansi-yellow-intense-fg ansi-bold">[</span>new_arg_name<span class="ansi-yellow-intense-fg ansi-bold">]</span> <span class="ansi-yellow-intense-fg ansi-bold">=</span> new_arg_value
<span class="ansi-green-intense-fg ansi-bold">---&gt; 91</span><span class="ansi-yellow-intense-fg ansi-bold">             </span><span class="ansi-green-intense-fg ansi-bold">return</span> func<span class="ansi-yellow-intense-fg ansi-bold">(</span><span class="ansi-yellow-intense-fg ansi-bold">*</span>args<span class="ansi-yellow-intense-fg ansi-bold">,</span> <span class="ansi-yellow-intense-fg ansi-bold">**</span>kwargs<span class="ansi-yellow-intense-fg ansi-bold">)</span>
<span class="ansi-green-fg">     92</span>         <span class="ansi-green-intense-fg ansi-bold">return</span> wrapper
<span class="ansi-green-fg">     93</span>     <span class="ansi-green-intense-fg ansi-bold">return</span> _deprecate_kwarg

<span class="ansi-green-intense-fg ansi-bold">C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\pandas\core\generic.py</span> in <span class="ansi-cyan-fg">astype</span><span class="ansi-blue-intense-fg ansi-bold">(self, dtype, copy, errors, **kwargs)</span>
<span class="ansi-green-fg">   3408</span>         <span class="ansi-red-intense-fg ansi-bold"># else, only a single dtype is given</span>
<span class="ansi-green-fg">   3409</span>         new_data = self._data.astype(dtype=dtype, copy=copy, errors=errors,
<span class="ansi-green-intense-fg ansi-bold">-&gt; 3410</span><span class="ansi-yellow-intense-fg ansi-bold">                                      **kwargs)
</span><span class="ansi-green-fg">   3411</span>         <span class="ansi-green-intense-fg ansi-bold">return</span> self<span class="ansi-yellow-intense-fg ansi-bold">.</span>_constructor<span class="ansi-yellow-intense-fg ansi-bold">(</span>new_data<span class="ansi-yellow-intense-fg ansi-bold">)</span><span class="ansi-yellow-intense-fg ansi-bold">.</span>__finalize__<span class="ansi-yellow-intense-fg ansi-bold">(</span>self<span class="ansi-yellow-intense-fg ansi-bold">)</span>
<span class="ansi-green-fg">   3412</span> 

<span class="ansi-green-intense-fg ansi-bold">C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\pandas\core\internals.py</span> in <span class="ansi-cyan-fg">astype</span><span class="ansi-blue-intense-fg ansi-bold">(self, dtype, **kwargs)</span>
<span class="ansi-green-fg">   3222</span> 
<span class="ansi-green-fg">   3223</span>     <span class="ansi-green-intense-fg ansi-bold">def</span> astype<span class="ansi-yellow-intense-fg ansi-bold">(</span>self<span class="ansi-yellow-intense-fg ansi-bold">,</span> dtype<span class="ansi-yellow-intense-fg ansi-bold">,</span> <span class="ansi-yellow-intense-fg ansi-bold">**</span>kwargs<span class="ansi-yellow-intense-fg ansi-bold">)</span><span class="ansi-yellow-intense-fg ansi-bold">:</span>
<span class="ansi-green-intense-fg ansi-bold">-&gt; 3224</span><span class="ansi-yellow-intense-fg ansi-bold">         </span><span class="ansi-green-intense-fg ansi-bold">return</span> self<span class="ansi-yellow-intense-fg ansi-bold">.</span>apply<span class="ansi-yellow-intense-fg ansi-bold">(</span><span class="ansi-blue-intense-fg ansi-bold">&#39;astype&#39;</span><span class="ansi-yellow-intense-fg ansi-bold">,</span> dtype<span class="ansi-yellow-intense-fg ansi-bold">=</span>dtype<span class="ansi-yellow-intense-fg ansi-bold">,</span> <span class="ansi-yellow-intense-fg ansi-bold">**</span>kwargs<span class="ansi-yellow-intense-fg ansi-bold">)</span>
<span class="ansi-green-fg">   3225</span> 
<span class="ansi-green-fg">   3226</span>     <span class="ansi-green-intense-fg ansi-bold">def</span> convert<span class="ansi-yellow-intense-fg ansi-bold">(</span>self<span class="ansi-yellow-intense-fg ansi-bold">,</span> <span class="ansi-yellow-intense-fg ansi-bold">**</span>kwargs<span class="ansi-yellow-intense-fg ansi-bold">)</span><span class="ansi-yellow-intense-fg ansi-bold">:</span>

<span class="ansi-green-intense-fg ansi-bold">C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\pandas\core\internals.py</span> in <span class="ansi-cyan-fg">apply</span><span class="ansi-blue-intense-fg ansi-bold">(self, f, axes, filter, do_integrity_check, consolidate, **kwargs)</span>
<span class="ansi-green-fg">   3089</span> 
<span class="ansi-green-fg">   3090</span>             kwargs<span class="ansi-yellow-intense-fg ansi-bold">[</span><span class="ansi-blue-intense-fg ansi-bold">&#39;mgr&#39;</span><span class="ansi-yellow-intense-fg ansi-bold">]</span> <span class="ansi-yellow-intense-fg ansi-bold">=</span> self
<span class="ansi-green-intense-fg ansi-bold">-&gt; 3091</span><span class="ansi-yellow-intense-fg ansi-bold">             </span>applied <span class="ansi-yellow-intense-fg ansi-bold">=</span> getattr<span class="ansi-yellow-intense-fg ansi-bold">(</span>b<span class="ansi-yellow-intense-fg ansi-bold">,</span> f<span class="ansi-yellow-intense-fg ansi-bold">)</span><span class="ansi-yellow-intense-fg ansi-bold">(</span><span class="ansi-yellow-intense-fg ansi-bold">**</span>kwargs<span class="ansi-yellow-intense-fg ansi-bold">)</span>
<span class="ansi-green-fg">   3092</span>             result_blocks <span class="ansi-yellow-intense-fg ansi-bold">=</span> _extend_blocks<span class="ansi-yellow-intense-fg ansi-bold">(</span>applied<span class="ansi-yellow-intense-fg ansi-bold">,</span> result_blocks<span class="ansi-yellow-intense-fg ansi-bold">)</span>
<span class="ansi-green-fg">   3093</span> 

<span class="ansi-green-intense-fg ansi-bold">C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\pandas\core\internals.py</span> in <span class="ansi-cyan-fg">astype</span><span class="ansi-blue-intense-fg ansi-bold">(self, dtype, copy, errors, values, **kwargs)</span>
<span class="ansi-green-fg">    469</span>     <span class="ansi-green-intense-fg ansi-bold">def</span> astype<span class="ansi-yellow-intense-fg ansi-bold">(</span>self<span class="ansi-yellow-intense-fg ansi-bold">,</span> dtype<span class="ansi-yellow-intense-fg ansi-bold">,</span> copy<span class="ansi-yellow-intense-fg ansi-bold">=</span><span class="ansi-green-intense-fg ansi-bold">False</span><span class="ansi-yellow-intense-fg ansi-bold">,</span> errors<span class="ansi-yellow-intense-fg ansi-bold">=</span><span class="ansi-blue-intense-fg ansi-bold">&#39;raise&#39;</span><span class="ansi-yellow-intense-fg ansi-bold">,</span> values<span class="ansi-yellow-intense-fg ansi-bold">=</span><span class="ansi-green-intense-fg ansi-bold">None</span><span class="ansi-yellow-intense-fg ansi-bold">,</span> <span class="ansi-yellow-intense-fg ansi-bold">**</span>kwargs<span class="ansi-yellow-intense-fg ansi-bold">)</span><span class="ansi-yellow-intense-fg ansi-bold">:</span>
<span class="ansi-green-fg">    470</span>         return self._astype(dtype, copy=copy, errors=errors, values=values,
<span class="ansi-green-intense-fg ansi-bold">--&gt; 471</span><span class="ansi-yellow-intense-fg ansi-bold">                             **kwargs)
</span><span class="ansi-green-fg">    472</span> 
<span class="ansi-green-fg">    473</span>     def _astype(self, dtype, copy=False, errors=&#39;raise&#39;, values=None,

<span class="ansi-green-intense-fg ansi-bold">C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\pandas\core\internals.py</span> in <span class="ansi-cyan-fg">_astype</span><span class="ansi-blue-intense-fg ansi-bold">(self, dtype, copy, errors, values, klass, mgr, raise_on_error, **kwargs)</span>
<span class="ansi-green-fg">    519</span> 
<span class="ansi-green-fg">    520</span>                 <span class="ansi-red-intense-fg ansi-bold"># _astype_nansafe works fine with 1-d only</span>
<span class="ansi-green-intense-fg ansi-bold">--&gt; 521</span><span class="ansi-yellow-intense-fg ansi-bold">                 </span>values <span class="ansi-yellow-intense-fg ansi-bold">=</span> astype_nansafe<span class="ansi-yellow-intense-fg ansi-bold">(</span>values<span class="ansi-yellow-intense-fg ansi-bold">.</span>ravel<span class="ansi-yellow-intense-fg ansi-bold">(</span><span class="ansi-yellow-intense-fg ansi-bold">)</span><span class="ansi-yellow-intense-fg ansi-bold">,</span> dtype<span class="ansi-yellow-intense-fg ansi-bold">,</span> copy<span class="ansi-yellow-intense-fg ansi-bold">=</span><span class="ansi-green-intense-fg ansi-bold">True</span><span class="ansi-yellow-intense-fg ansi-bold">)</span>
<span class="ansi-green-fg">    522</span>                 values <span class="ansi-yellow-intense-fg ansi-bold">=</span> values<span class="ansi-yellow-intense-fg ansi-bold">.</span>reshape<span class="ansi-yellow-intense-fg ansi-bold">(</span>self<span class="ansi-yellow-intense-fg ansi-bold">.</span>shape<span class="ansi-yellow-intense-fg ansi-bold">)</span>
<span class="ansi-green-fg">    523</span> 

<span class="ansi-green-intense-fg ansi-bold">C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\pandas\core\dtypes\cast.py</span> in <span class="ansi-cyan-fg">astype_nansafe</span><span class="ansi-blue-intense-fg ansi-bold">(arr, dtype, copy)</span>
<span class="ansi-green-fg">    623</span>     <span class="ansi-green-intense-fg ansi-bold">elif</span> arr<span class="ansi-yellow-intense-fg ansi-bold">.</span>dtype <span class="ansi-yellow-intense-fg ansi-bold">==</span> np<span class="ansi-yellow-intense-fg ansi-bold">.</span>object_ <span class="ansi-green-intense-fg ansi-bold">and</span> np<span class="ansi-yellow-intense-fg ansi-bold">.</span>issubdtype<span class="ansi-yellow-intense-fg ansi-bold">(</span>dtype<span class="ansi-yellow-intense-fg ansi-bold">.</span>type<span class="ansi-yellow-intense-fg ansi-bold">,</span> np<span class="ansi-yellow-intense-fg ansi-bold">.</span>integer<span class="ansi-yellow-intense-fg ansi-bold">)</span><span class="ansi-yellow-intense-fg ansi-bold">:</span>
<span class="ansi-green-fg">    624</span>         <span class="ansi-red-intense-fg ansi-bold"># work around NumPy brokenness, #1987</span>
<span class="ansi-green-intense-fg ansi-bold">--&gt; 625</span><span class="ansi-yellow-intense-fg ansi-bold">         </span><span class="ansi-green-intense-fg ansi-bold">return</span> lib<span class="ansi-yellow-intense-fg ansi-bold">.</span>astype_intsafe<span class="ansi-yellow-intense-fg ansi-bold">(</span>arr<span class="ansi-yellow-intense-fg ansi-bold">.</span>ravel<span class="ansi-yellow-intense-fg ansi-bold">(</span><span class="ansi-yellow-intense-fg ansi-bold">)</span><span class="ansi-yellow-intense-fg ansi-bold">,</span> dtype<span class="ansi-yellow-intense-fg ansi-bold">)</span><span class="ansi-yellow-intense-fg ansi-bold">.</span>reshape<span class="ansi-yellow-intense-fg ansi-bold">(</span>arr<span class="ansi-yellow-intense-fg ansi-bold">.</span>shape<span class="ansi-yellow-intense-fg ansi-bold">)</span>
<span class="ansi-green-fg">    626</span> 
<span class="ansi-green-fg">    627</span>     <span class="ansi-green-intense-fg ansi-bold">if</span> dtype<span class="ansi-yellow-intense-fg ansi-bold">.</span>name <span class="ansi-green-intense-fg ansi-bold">in</span> <span class="ansi-yellow-intense-fg ansi-bold">(</span><span class="ansi-blue-intense-fg ansi-bold">&#34;datetime64&#34;</span><span class="ansi-yellow-intense-fg ansi-bold">,</span> <span class="ansi-blue-intense-fg ansi-bold">&#34;timedelta64&#34;</span><span class="ansi-yellow-intense-fg ansi-bold">)</span><span class="ansi-yellow-intense-fg ansi-bold">:</span>

<span class="ansi-green-intense-fg ansi-bold">pandas\_libs\lib.pyx</span> in <span class="ansi-cyan-fg">pandas._libs.lib.astype_intsafe</span><span class="ansi-blue-intense-fg ansi-bold">()</span>

<span class="ansi-green-intense-fg ansi-bold">pandas/_libs/src\util.pxd</span> in <span class="ansi-cyan-fg">util.set_value_at_unsafe</span><span class="ansi-blue-intense-fg ansi-bold">()</span>

<span class="ansi-red-intense-fg ansi-bold">TypeError</span>: int() argument must be a string, a bytes-like object or a number, not &#39;NoneType&#39;</pre>
</div>
</div>

</div>
</div>

</div>
<div class="cell border-box-sizing text_cell rendered"><div class="prompt input_prompt">
</div>
<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<h3 id="Expected-behavior-should-be-4-rows-of-all-0">Expected behavior should be 4 rows of all 0<a class="anchor-link" href="#Expected-behavior-should-be-4-rows-of-all-0">&#182;</a></h3>
</div>
</div>
</div>
    </div>
  </div>
</body>

 

</html>

**Comment by janmotl** [comment]
Thank you for the bug report.

It looks like the current development code treats these scenarios correctly. Since it will take a while until a new release is made, I have to suggest to use the code in the master branch.

**Comment by wdm0006** [comment]
This will be in v1.4.0, working on closing out that release now, so closing this issue.
