### ISSUE TITLE
Are you sure ahout the speed of target-encoding？

### ISSUE THREAD

**Issue by jiangxiaoshaui** [scikit-learn-contrib/categorical-encoding#157]
I actually didn't know what had happened, but it's real a thing. When i used target encoding transform my 'id' ,it was fifth time, yes, it's still work, but it took me the whole afternoon.I think i got a problem.

**Comment by janmotl** [comment]
Which version of the library do you use? Is it from pip or the master branch on git?

**Comment by janmotl** [comment]
The version in the master branch should be significantly faster than the version from pip.

**Comment by jiangxiaoshaui** [comment]
> 主分支中的版本应该比来自pip的版本快得多。
thanks
