### ISSUE TITLE
Pickling TargetEncoder

### ISSUE THREAD

**Issue by WithPrecedent** [scikit-learn-contrib/categorical-encoding#158]
I'm having difficulty applying a fit TargetEncoder to new data. For the model creation, these are the key portions of my code:

encoder = ce.TargetEncoder(cols = cols)
encoder.fit(X, y)
X = encoder.transform(X.reset_index(drop = True)) 
pickle.dump(encoder, open(export_path, 'wb'))

I also tried assigning the fit encoder to a variable and pickling that variable (hoping it would make a difference):

encoder = ce.TargetEncoder(cols = cols)
fit_encoder = encoder.fit(X, y)
X = encoder.transform(X.reset_index(drop = True)) 
pickle.dump(fit_encoder, open(export_path, 'wb'))

When I load the new data into a prediction module, this is my code:
encoder = pickle.load(open(paths.encoder, 'rb'))
data = encoder.transform(data.reset_index(drop = True))

When I print(encoder) in the prediction module, this is what I get:
TargetEncoder(cols=[variable list],
       drop_invariant=False, handle_unknown='impute', impute_missing=True,
       min_samples_leaf=1, return_df=True, smoothing=1.0, verbose=0)

But regardless of which code I use for the model creation and pickling, 'transform' doesn't actually change the new data. So, when trying to get predicted probabilities from my xgboost model for the new data, it gives me a ValueError. To debug, I also have printed the datatypes immediately before and after the transform in the model and prediction modules. But the datatypes only change in the modeling module (and not the prediction module)

I assume I'm doing something wrong in the pickling process because I'm not too familiar with pickling models and algorithms, but couldn't find any documentation. If pickle is not the preferred storage medium, I'm open to using something else. Any help would be appreciated.

**Comment by janmotl** [comment]
I tested the master branch against a following test:
```python
    def test_pickle(self):
        encoder = encoders.TargetEncoder()
        encoder.fit(X, y)
        result1 = encoder.transform(X_t)

        pickled = pickle.dumps(encoder)
        encoder = pickle.loads(pickled)
        result2 = encoder.transform(X_t)

        self.assertTrue(result2.equals(result1))
```

And it worked. Hence, I would suggest to try the target encoder from the master branch (and not from the release).

**Comment by WithPrecedent** [comment]
Thanks. Everything seems to work now (with dumps/loads and dump/load).
