### ISSUE TITLE
Add leave-one-out encoding

### ISSUE THREAD

**Issue by wdm0006** [scikit-learn-contrib/categorical-encoding#16]
A popular kaggle technique for encoding categorical variables is 'leave-one-out', shown here:

http://nycdatascience.com/featured-talk-1-kaggle-data-scientist-owen-zhang/

https://www.kaggle.com/c/caterpillar-tube-pricing/forums/t/15748/strategies-to-encode-categorical-variables-with-many-categories?forumMessageId=143154

It would be cool to add that into the library to evaluate it against other methods.

**Comment by geezhawk** [comment]
I'll tackle this one if no one else is on it yet.

**Comment by wdm0006** [comment]
Awesome, let me know if you have any questions along the way!

**Comment by hbghhy** [comment]
I want to try this, but i wonder what should i do when i meet a never seen category?
Encoder it as the mean of y in whole train data or something else?

**Comment by wdm0006** [comment]
@hbghhy awesome! In one-hot, you'll see an example of how we've handled this in the past. There we have options of raising exceptions, ignoring the samples, or imputing something to indicate 'unknown'.  For this, imputing the mean of whole training data may be a good approach for 'unknown'.

**Comment by hbghhy** [comment]
@wdm0006 ,I just pull a new request about it. You can see is there something wrong.

**Comment by wdm0006** [comment]
Fixed!
