### ISSUE TITLE
New target encoders

### ISSUE THREAD

**Issue by janmotl** [scikit-learn-contrib/categorical-encoding#164]
Branch `new_target_encoders` contains 3 new variants of TargetEncoder (log-odds ratio estimated with empirical Bayes, likelihood estimated with empirical Bayes, and m-probability estimate). They are all quite similar. But since all the contrast encoders (like SumEncoder or HelmertEncoder) have their own separate file, so do these.

Should they be added into the master branch?

**Comment by PGijsbers** [comment]
Hi there, I happened upon this issue as I was looking for these different smoothing functions with target encoding. First off thanks for the work :)

However, I did feel the need to point out that the amount of code duplication that exists with the presented setup is (in my opinion) not a good idea for long term management of the package. I would strongly encourage sharing implementations for methods that are essentially the same.

For example, create one general target encoder class that takes a smoothing method as input. Define different smoothing methods:
```
def m_smoothing(m):
     def smooth_func(n):
        return n / (n+m)

def exp_smoothing(f, k):
    def smooth_func(n):
        return 1/(1+exp(-(n-k)/f))
```
and the general class:
```
class TargetEncoder:
    def __init__(self, ..., smoothing):
        self._smooth = smoothing
        ....
    def transform(X):
        ....
        x_transformed = self._smooth(n_in_cat)*map_posterior[cat_level] + (1-self._smooth(n_in_cat))*map_prior(class)
     
```
a user would then specify smoothing when initializing the target encoder:
```
from category_encoders import TargetEncoder, exp_smoothing
target_enc = TargetEncoder(..., smoothing=exp_smoothing(f=1, k=1))
```
Hope it helps (and the psuedo-code is not too vague). If you need a help refactoring I also might be able to make some time for that (but not sure when).

**Comment by janmotl** [comment]
Another approach could be to move all the shared code into a common class and inherit from this common class. If the common class was designed reasonably, the derived classes would not contain a lot of duplicate code. 

What has to be considered:
1. Each encoder performs 'handle_missing=value' and 'handle_unknown=value' slightly differently. Some impute with zero. Other with the prior probability.
2. Inheritance from "TargetEncoder" could be a reasonable way how to programmatically differentiate between target encoders and non-target encoders (#166).
3. The estimation methods (and their arguments) have to be documented. Multiple classes provide  more space than a single class. On the other end, documentation is not inherited. Hence, significant portion of the documentation would remain duplicated. But I can live with that.

I do not know which of the approaches is better. Either way, help would be greatly appreciated.

**Comment by janmotl** [comment]
Ok. Go ahead with the code.

**Comment by PGijsbers** [comment]
Cool :) though as noted before I don't know when I will have the time to do so. Do you think it makes sense to fork off the `new_target_encoders` branch or create a new branch in the fork?

**Comment by janmotl** [comment]
I would fork the branch. But whatever works for you.

**Comment by janmotl** [comment]
I merged James-Stein estimators together. And that has left m-estimator alone. The code is now in the master branch.
