### ISSUE TITLE
OrdinalEncoder has extraneous nan column when using handle_missing = nan

### ISSUE THREAD

**Issue by datarian** [scikit-learn-contrib/categorical-encoding#180]
I discovered this recently. It's not a real problem because it's a constant column with all zeros, but still it's not nice and might lead to problems because there's an extra column added and hence dimensions not as expected.

I suspect it originates in the crude way that feature_names are constructed during fit() (which I have to blame myself for...) but did not have the time to really dig into it yet.

Since other encoders depend on OrdinalEncoder, this propagates. Maybe it should be tackled before the next release? Willing to look into it, but can't commit to a timeframe currently.

Just more of a note right now, will add more info soon.

**Comment by janmotl** [comment]
Hi @datarian, can you elaborate?

When I run:
```python
np_X = th.create_array(n_rows=100)
np_X_t = th.create_array(n_rows=50, extras=True)
np_y = np.random.randn(np_X.shape[0]) > 0.5

def test_handle_missing_return_nan_np(self):
    enc = encoders.OrdinalEncoder(handle_missing='return_nan')
    enc.fit(np_X, np_y)
    result = enc.transform(np_X_t)
    self.assertEqual(np_X_t.shape[1], len(result.columns)) # the count of columns remains identical
```
the last column is constant. But it is supposed to be constant because the feature is constant in `np_X_t`.

Just to be sure, we can run it on data without the last column being constant:
```python
X = th.create_dataset(n_rows=100)
X_t = th.create_dataset(n_rows=50, extras=True)
np_y = np.random.randn(np_X.shape[0]) > 0.5
y = pd.DataFrame(np_y)

def test_handle_missing_return_nan(self):
    enc = encoders.OrdinalEncoder(handle_missing='return_nan')
    enc.fit(X, y)
    result = enc.transform(X_t)
    self.assertEqual(len(X_t.columns), len(result.columns)) # the count of columns remains same
```
Also works as expected.

**Comment by datarian** [comment]
Actually, it is the encoders that rely on OrdinalEncoder that have the extra column. This happens because they instantiate OrdinalEncoder with `handle_missing='value'`. Will investigate this further and return with a pull request.
