### ISSUE TITLE
Issue with `TargetEcoder` when pandas index is not sorted

### ISSUE THREAD

**Issue by michael135** [scikit-learn-contrib/categorical-encoding#181]
Very simplie example:

```import category_encoders as ce
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
import pandas as pd

boston = load_boston()
y = pd.Series(boston.target)
X = pd.DataFrame(boston.data, columns=boston.feature_names)

X_train, X_test, y_train, y_test = train_test_split(X, y,\
                                                    test_size=0.33, random_state=123)


enc = ce.TargetEncoder(cols=['CHAS', 'RAD'])
X_encoded = enc.fit_transform(X_train, y_train)
```
Has the following error:
>> ```IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match```

**Comment by michael135** [comment]
The solution:
is to add the follwing line:
 ```X_train.reset_index(drop=True, inplace=True)```

I would suggest to add, some mention to documentation, regarding the issue with dataframe indexes.

**Comment by janmotl** [comment]
Thank you for the report. I believe this issue is already fixed in the current master version. 

@wdm0006: Once a new release is made, this issue can be closed.

**Comment by janmotl** [comment]
Version 2.0.0 is out.
