### ISSUE TITLE
Support full transform for OneHotEncoder

### ISSUE THREAD

**Issue by justkunz** [scikit-learn-contrib/categorical-encoding#19]
Currently, `OneHotEncoder.transform` only adds columns for the categories that are passed in, not for all the categories present. This breaks sklearn pipelines when applied to a few rows because OneHotEncoder.transform returns the wrong shape. The example from [this stackoverflow post](http://stackoverflow.com/questions/39970517/how-to-encode-two-pandas-dataframes-according-to-the-same-dummy-vectors/39973405#39973405) shows how `fit_transform` returns 5 columns, but `transform` only returns 3 columns when it's called on 2 rows. 

Ideally, `transform` should behave as follows in that stackoverflow example, so it can be used in sklearn pipelines properly:
```
df_test = pd.DataFrame({'cat1':['A','N',],'cat2':['T','B']})
df_test_trans = enc_ohe.transform(df_test)

print(df_test_trans)

   cat1_0  cat1_1  cat1_2  cat1_3 cat2
0       0       1       0       0    T
1       0       0       0       1    B
```

**Comment by wdm0006** [comment]
Yeah, that makes sense.  In `get_dummies` in one_hot we build up the encoded columns based on what is in the passed in `X`, but really ought to get the categories from the pre-trained `OrdinalEncoder` that got built in `fit`.  I think that would solve this issue. 

Is the assumption that all categories you want to encode are present in the dataset you pass to `fit` reasonable?

**Comment by justkunz** [comment]
Yes, @wdm0006 your assumption is correct, all categories to encode should be passed in the dataset to `fit`.

**Comment by wdm0006** [comment]
Are you interested in working on a PR @justkunz? If not I'll try to work on this soon.

**Comment by justkunz** [comment]
@wdm0006 I can get a quick PR up.

**Comment by wdm0006** [comment]
Fixed by #20

**Comment by wdm0006** [comment]
Will do a new release soon, would like to try to fix #18 beforehand though if possible.

**Comment by justkunz** [comment]
@wdm0006 what's the status of the 1.2.4 release?

**Comment by wdm0006** [comment]
I need to do a docs update with some of the recent PRs, but will try to get it out this week.

**Comment by wdm0006** [comment]
@justkunz, just released it.

**Comment by justkunz** [comment]
Thanks @wdm0006!
