### ISSUE TITLE
your algorithm for categorical values calculation algorithm is mistaken

### ISSUE THREAD

**Issue by Sandy4321** [scikit-learn-contrib/categorical-encoding#205]
as catboost team state here
https://github.com/catboost/catboost/issues/948
http://contrib.scikit-learn.org/categorical-encoding/catboost.html
your algorithm for categorical values calculation algorithm is mistaken
you can use catboost code to understand what algorithms is and how to fix mistakes

**Comment by janmotl** [comment]
Can you provide an example where the output is wrong and how it should look like?

This example seems to pass:
```python
    def test_catBoost_reference(self):
        # The reference is from:
        #   https://catboost.ai/docs/concepts/algorithm-main-stages_cat-to-numberic.html
        # paragraph:
        #     Transforming categorical features to numerical features in classification
        # as obtained on 17 Aug 2019.
        X = pd.DataFrame({'col1': ['rock', 'indie', 'rock', 'rock', 'pop', 'indie', 'rock']})
        y = pd.Series([0, 0, 1, 1, 1, 0, 0])
        enc = encoders.CatBoostEncoder()
        obtained = enc.fit_transform(X, y)
        prior = 3./7  # Since we do not support prior passing, we replace the prior in the reference = 0.05 with the sample prior = 3/7.
        self.assertEqual(list(obtained['col1']), [prior, prior, prior/2, (1+prior)/3, prior, prior/2, (2+prior)/4])
```

**Comment by Sandy4321** [comment]
It is the point, I gave you example how mistaken it is. Very detailed example with pictures with calculations and you confessed it is mistaken

**Comment by janmotl** [comment]
Can you, please, provide a unit test? I.e.: code where the current implementation fails and which also contains the desired output?

Why do I ask: I followed the links but I always get lost. @annaveronika says that there is an error in our code and I trust her. She also says that their documentation is correct. But the result that I am getting from CatBoostEncoder seems to match their documentation (up to the value of the prior). 
A unit test could make the issue evident.

**Comment by Sandy4321** [comment]
my guess @annaveronika talking about conceptual mistakes in you algorithm , but not  in code
"She also says that their documentation is correct."
no, I showed  her that catboost documentation is mistaken, at first she agreed and then she refuses  that her  documentation is mistaken. You can see on my prove in this link
https://github.com/catboost/catboost/issues/836
just review images with calculations.
She sent me to original paper , paper is messy, seems to be they hide something 
she also references to this link
https://github.com/catboost/catboost/issues/436
but this not helping neither
She also suggests to see from code
https://github.com/catboost/catboost/blob/master/catboost/libs/algo/online_ctr.cpp
 but code is messy as well, even there is no comments
best way to extract part of code related to categorical encoding and run it as stand alone code 
This way we will be able to run some data examples and see how exactly all works
can you do it ?
if you share only function related to categorical encoding  ( it may be max 100 lines ), I can take part in investigation what and how they doing, though for long time I did not used C.

All looks fishy , since categorical-encoding is essential scientific part of all this project of catboos, but they mislead people how it works. 
I asked her , in which parameter they return encoded values and she wrote me they do not share new transformer data !!!

In any case I am glad you are interested in this issue , since in order to use this catboos properly we have to understand how it works, 
and as more they hide it as more it is interesting what they hide  or they by themselves do not understand how it works , since it would be easier to clear open/explain  this information than to be this kind of not nice people....
We are not alone who try to understand how it works
you can see this link as well
 https://www.youtube.com/watch?v=hqYQ8Yj9vB0&feature=youtu.be
Liam Kirwin: How am I going to deal with all of these cats | PyData London 2019

**Comment by janmotl** [comment]
I have read thru [CatBoost: unbiased boosting with categorical features](https://arxiv.org/abs/1706.09516) and I still do not see the issue. Sure, our code internally uses method names from LOOEncoder (that's not nice). And our `a` from equation 5 is fixed to `1` why they have it as a parameter. 

I watched the video. I was not able to reproduce the results from what we can see at 35:03.

The calculation in blue from the photos is using a mixture of offline (in the nominator of equation 5) and online (in the denominator of equation 5) processing. The documentation, the article and our implementation use online processing in the both, the nominator and the denominator.

**Comment by janmotl** [comment]
Fixed the method names and turned `a` into a parameter in https://github.com/scikit-learn-contrib/categorical-encoding/commit/25accdc9b5b1998ae317e2bcd120464a7b1027bf.
