### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by pouyana** [scikit-learn-contrib/categorical-encoding#211]
Hi,

the documentation in https://contrib.scikit-learn.org/categorical-encoding/ordinal.html is outdated. 

There, the mapping is defined as:

```
[{‘col’: ‘col1’, ‘mapping’: [(None, 0), (‘a’, 1), (‘b’, 2)]}]
```

but in the code https://github.com/scikit-learn-contrib/categorical-encoding/blob/master/category_encoders/ordinal.py#L35 it is defined as:

```
[{'col': 'col1', 'mapping': {None: 0, 'a': 1, 'b': 2}}]
```

could you please update it to reflect this change.

**Comment by janmotl** [comment]
Thank you. We will update it at the next opportunity.

**Comment by janmotl** [comment]
Updated
