### ISSUE TITLE
HelmertEncoder handle_missing default is 'indicator'.

### ISSUE THREAD

**Issue by rohitgr7** [scikit-learn-contrib/categorical-encoding#212]
Hi,

In the [documentation](https://contrib.scikit-learn.org/categorical-encoding/helmert.html) default value for `handle_missing` and `handle_unknown` is `value`.

But in the [code](https://github.com/scikit-learn-contrib/categorical-encoding/blob/25accdc9b5b1998ae317e2bcd120464a7b1027bf/category_encoders/helmert.py#L88), it is `indicator`.

**Comment by janmotl** [comment]
I propose to change the default behaviour in code to `value` because that's the default behavior of the related encoders like SumEncoder, PolynomialEncoder, BackwardDifferenceEncoder and OneHotEncoder. Are you ok with that?

**Comment by rohitgr7** [comment]
Ok. Should I change it in my code while creating the instance of `HelmertEncoder` or do a PR too??

**Comment by janmotl** [comment]
I fixed it in the master branch. Thank you for the report.
