### ISSUE TITLE
do not ignore unknown categories : known problem in scikit learn for OrdinalEncoder

### ISSUE THREAD

**Issue by Sandy4321** [scikit-learn-contrib/categorical-encoding#234]
do you have solution for known problem in scikit learn for OrdinalEncoder
https://github.com/scikit-learn/scikit-learn/issues/13488

they do not ignore unknown categories value as OneHotEncoder does
since in real live, there are often many differences between train and data test?
as stated above by @ogrisel : Personally I find this issue really annoying

hopefully you have solution ?

**Comment by janmotl** [comment]
The implemented options in OrdinalEncoder are:
```
handle_unknown: str
     options are 'error', 'return_nan' and 'value', defaults to 'value', which will impute the category -1.
```

So far it was enough. The encoders that build on top of OrdinalEncoder just use `'return_nan'` and use their own logic to return something sane (the keyword arguments for `'handle_unknown'`  and their meaning in the general sense are the same over all the encoders, but the details necessarily differ). 

The option of `handle_unknown="treat_as_rare"` in the original thread is nice. We currently work on a cross-validation (CV) wrapper #233 that, among other, solves the issue that the `-1` does not appear in the training data. The nice thing about the CV is that you do not have to fine-tune anything (like `min_frequency=5`). But it can impact the runtime.

**Comment by Sandy4321** [comment]
The implemented options in OrdinalEncoder are:

handle_unknown: str
     options are 'error', 'return_nan' and 'value', defaults to 'value', which will impute the category -1.
So far it was enough
Great
And hopefully you have code examples
For toy data?

**Comment by janmotl** [comment]
Check the test files. For example, `test_handle_unknown_have_new_value_expect_negative_1` in `test_ordinal.py`:

```python
        train = pd.DataFrame({'city': ['chicago', 'st louis']})
        test = pd.DataFrame({'city': ['chicago', 'los angeles']})
        expected = [1, -1]

        enc = encoders.OrdinalEncoder()
        enc.fit(train)
        result = enc.transform(test)['city'].tolist()

        self.assertEqual(expected, result)
```
