### ISSUE TITLE
TargetEncoder produces missing values with pandas categorical data

### ISSUE THREAD

**Issue by PGijsbers** [scikit-learn-contrib/categorical-encoding#235]
Using the TargetEncoder to transform data with unknown categorical values and `handle_unknown='value'` (default) can produce `NaN`-values. This happens when the input data is a pandas DataFrame with the categorical column of type "category":

```python
import pandas as pd
from category_encoders import TargetEncoder

x = pd.DataFrame(['A','A','B'], dtype='category')
y = pd.Series([0.1,0.1,0.2])
te = TargetEncoder(handle_unknown='value').fit(x.loc[[0, 1]], y.loc[[0, 1]])
te.transform(x.loc[[2]])
>>> NaN
```

When the data is passed in as dtype "object" it works as expected:

```python
import pandas as pd
from category_encoders import TargetEncoder

x = pd.DataFrame(['A','A','B'], dtype='object')  # Notice changed dtype
y = pd.Series([0.1,0.1,0.2])
te = TargetEncoder(handle_unknown='value').fit(x.loc[[0, 1]], y.loc[[0, 1]])
te.transform(x.loc[[2]])
>>> 0.1
```

**Comment by PGijsbers** [comment]
I think it has to do with how the OrdinalEncoder constructs the mapping for "category" variables.

**Comment by janmotl** [comment]
I can reproduce the issue.

And this works:
```python
import pandas as pd
from category_encoders import TargetEncoder

x = pd.DataFrame(pd.Categorical(['A', 'A', 'B']))
y = pd.Series([0.1,0.1,0.2])
te = TargetEncoder(handle_unknown='value').fit(x.loc[[0, 1]], y.loc[[0, 1]])
te.transform(x.loc[[2]])
>>> 0.1
```
A PR would be appreciated. The current treatment of the categorical type is merely something that seemed to work. But I would expect:
```python
x = pd.DataFrame(['A','A','B'], dtype='category')
```
to also return 0.1 in the end.

OrdinalEncoder is a good place to change the behaviour.

**Comment by PGijsbers** [comment]
To be clear: we would like to construct a mapping in the OrdinalEncoder based on the data (values) passed into `fit` and ignore the meta-data of the categorical dtype that specifies all known categorical values? i.e. instead of [this](https://github.com/scikit-learn-contrib/categorical-encoding/blob/4a57405d2a4646fe5aef81c8530e3e1d0f6e885f/category_encoders/ordinal.py#L324) use e.g.  `X[col].unique()` to decide what values to include in the mapping.

**Comment by janmotl** [comment]
I get it now. The usage of `X[col].unique()` seems to be to a reasonable way how to get a consistent behaviour.
