### ISSUE TITLE
How Leave-One-Out-Encoder call k-folds CV?

### ISSUE THREAD

**Issue by ws15145177388** [scikit-learn-contrib/categorical-encoding#240]
The model will be obviously over-fitting after eave-One-Out-Encoder, How to set k-fold cross validation for functions?

**Comment by janmotl** [comment]
You may use `NestedCVWrapper` defined in `category_encoders/wrapper.py`. This a new class. So, it is currently only in the master branch (and not in any release).

Let us know whether it needs some more work.
