### ISSUE TITLE
re-using pickled/saved encoders

### ISSUE THREAD

**Issue by davidsbatista** [scikit-learn-contrib/categorical-encoding#26]
I've trained a model, for which I use the one-hot-encoder, and let's say a categorical variable, e.g. `device_type`, had 20 possible values, the trained model is now expecting to see, among other columns, 20 columns related with the values of `device_type`, i.e.:

 `device_type_0, device_type_1, ..., device_type_20` 

I also saved/pickled this trained model as well as the one-hot-encoder.

I now have new data coming, and the `device_type`, for this new data, only has 10 possible values. I was assuming that by applying the pickled/saved one-hot-encoder which I used before, I would see the same 20 columns related with the values of `device_type`, i.e.:

 `device_type_0, device_type_1, ..., device_type_20`

But I only see 10 `device_type_X` columns, i.e., only for the values presente in the new data.

Is there something I'm missing when I instantiate the encoder, or a parameter I'm missing when applying the fit, or simply this functionality is not implemented ?

**Comment by davidsbatista** [comment]
mea culpa! I was simple doing `fit_transform`, thanks for the reply.

One more question, how does this pickled `one-hot-encoder` will handle unseen values for a categorical variable?

**Comment by wdm0006** [comment]
you can pass `handle_unknown` as `error`, `impute` or `ignore` and it will either raise an exception, impute a class for "unknown" or just ignore that sample outright, respectively.
