### ISSUE TITLE
convert_objects is deprecated

### ISSUE THREAD

**Issue by dbarrundiag** [scikit-learn-contrib/categorical-encoding#28]
```
category_encoders\utils.py:30: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
 X = X.convert_objects(convert_numeric=True)`
```

I'm using the following:
```
pandas: 0.18.0
scikit: 0.18.1
```

**Comment by wdm0006** [comment]
Ah yeah, noted, thanks for the ticket. Any interest in working on a PR for this?

**Comment by milanogc** [comment]
When will this fix be released?

**Comment by wdm0006** [comment]
I was hoping to fix #21 first, but that looks to have fallen off radar, I'll try to hack something together and get a release out this week.

**Comment by milanogc** [comment]
That's perfect, thank you!

**Comment by wdm0006** [comment]
@milanogc v1.2.5 is out on pypi and has this fix.

**Comment by milanogc** [comment]
Awesome! Thanks!
