### ISSUE TITLE
conda install currently breaks when using python 3.6

### ISSUE THREAD

**Issue by joseph-jnl** [scikit-learn-contrib/categorical-encoding#31]
UnsatisfiableError: The following specifications were found to be in conflict:
  - category_encoders -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

**Comment by wdm0006** [comment]
hm... @bollwyvl do you know what this would be? I don't know conda particularly well.

**Comment by joseph-jnl** [comment]
I think the output for 'conda info category_encoders' suggests there isn't a package built for python 3.6 yet on conda forge.

category_encoders 1.2.2 py27_0
------------------------------
file name   : category_encoders-1.2.2-py27_0.tar.bz2
name        : category_encoders
version     : 1.2.2
build string: py27_0
build number: 0
channel     : conda-forge
size        : 21 KB
arch        : x86_64
license     : BSD-3-Clause
license_family: BSD
md5         : 63ed69d36cff5e09e0d49ab778a5dc63
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/category_encoders-1.2.2-py27_0.tar.bz2
dependencies:
    numpy >=1.9.0
    pandas >=0.16.0
    patsy >=0.4.0
    python 2.7*
    scikit-learn >=0.15.0
    scipy >=0.9
    statsmodels >=0.6.0

category_encoders 1.2.2 py34_0
------------------------------
file name   : category_encoders-1.2.2-py34_0.tar.bz2
name        : category_encoders
version     : 1.2.2
build string: py34_0
build number: 0
channel     : conda-forge
size        : 21 KB
arch        : x86_64
license     : BSD-3-Clause
license_family: BSD
md5         : f3212fd6ed0ed15146858489c4330758
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/category_encoders-1.2.2-py34_0.tar.bz2
dependencies:
    numpy >=1.9.0
    pandas >=0.16.0
    patsy >=0.4.0
    python 3.4*
    scikit-learn >=0.15.0
    scipy >=0.9
    statsmodels >=0.6.0

category_encoders 1.2.2 py35_0
------------------------------
file name   : category_encoders-1.2.2-py35_0.tar.bz2
name        : category_encoders
version     : 1.2.2
build string: py35_0
build number: 0
channel     : conda-forge
size        : 21 KB
arch        : x86_64
license     : BSD-3-Clause
license_family: BSD
md5         : bb02504c5fd5293715df23e2bb3fa24b
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/category_encoders-1.2.2-py35_0.tar.bz2
dependencies:
    numpy >=1.9.0
    pandas >=0.16.0
    patsy >=0.4.0
    python 3.5*
    scikit-learn >=0.15.0
    scipy >=0.9
    statsmodels >=0.6.0

category_encoders 1.2.3 py27_0
------------------------------
file name   : category_encoders-1.2.3-py27_0.tar.bz2
name        : category_encoders
version     : 1.2.3
build string: py27_0
build number: 0
channel     : conda-forge
size        : 21 KB
arch        : x86_64
has_prefix  : False
license     : BSD-3-Clause
license_family: BSD
md5         : d8cbae74dd25a705f565949c4c356b7d
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/category_encoders-1.2.3-py27_0.tar.bz2
dependencies:
    numpy >=1.8.0
    pandas >=0.15.0
    patsy >=0.4.0
    python 2.7*
    scikit-learn >=0.15.0
    scipy >=0.9
    statsmodels >=0.6.0

category_encoders 1.2.3 py34_0
------------------------------
file name   : category_encoders-1.2.3-py34_0.tar.bz2
name        : category_encoders
version     : 1.2.3
build string: py34_0
build number: 0
channel     : conda-forge
size        : 22 KB
arch        : x86_64
has_prefix  : False
license     : BSD-3-Clause
license_family: BSD
md5         : db69f6cb82c45baf285015c4bd6bfdd0
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/category_encoders-1.2.3-py34_0.tar.bz2
dependencies:
    numpy >=1.8.0
    pandas >=0.15.0
    patsy >=0.4.0
    python 3.4*
    scikit-learn >=0.15.0
    scipy >=0.9
    statsmodels >=0.6.0

category_encoders 1.2.3 py35_0
------------------------------
file name   : category_encoders-1.2.3-py35_0.tar.bz2
name        : category_encoders
version     : 1.2.3
build string: py35_0
build number: 0
channel     : conda-forge
size        : 224 KB
arch        : x86_64
has_prefix  : False
license     : BSD-3-Clause
license_family: BSD
md5         : 325e15445ea196b68642bf25828b34cc
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/category_encoders-1.2.3-py35_0.tar.bz2
dependencies:
    numpy >=1.8.0
    pandas >=0.15.0
    patsy >=0.4.0
    python 3.5*
    scikit-learn >=0.15.0
    scipy >=0.9
    statsmodels >=0.6.0

**Comment by wdm0006** [comment]
There have been some updates in the conda repo on this, is your issue resolved now?

**Comment by joseph-jnl** [comment]
It is - thanks for the quick turnaround!

**Comment by wdm0006** [comment]
Yep, thanks @bollwyvl!

**Comment by bollwyvl** [comment]
Yeah, sorry for the delay, friends! You can definitely bother us (me, new maintainer @nirajd, who anticipated your need, and anyone else we can cajole into maintain packaging!) [over here](https://github.com/conda-forge/category_encoders-feedstock) for conda-related issues!
