### ISSUE TITLE
References hyperlink is deprecated

### ISSUE THREAD

**Issue by leopeng1995** [scikit-learn-contrib/categorical-encoding#32]
http://contrib.scikit-learn.org/categorical-encoding/backward_difference.html
https://github.com/scikit-learn-contrib/categorical-encoding/blob/master/category_encoders/backward_difference.py

> [1] Contrast Coding Systems for categorical variables.  UCLA: Statistical Consulting Group. from
http://www.ats.ucla.edu/stat/r/library/contrast_coding.

This hyperlink is deprecated and moved to:

https://stats.idre.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/

**Comment by dennisobrien** [comment]
This link is still referenced a few places in the code.
- [backward_difference.py](https://github.com/scikit-learn-contrib/categorical-encoding/blob/3c03f8eba2df26be3e0b15814a1e281dec0b0938/category_encoders/backward_difference.py#L80)
- [helmert.py](https://github.com/scikit-learn-contrib/categorical-encoding/blob/3c03f8eba2df26be3e0b15814a1e281dec0b0938/category_encoders/helmert.py#L80)
- [polynomial.py](https://github.com/scikit-learn-contrib/categorical-encoding/blob/3c03f8eba2df26be3e0b15814a1e281dec0b0938/category_encoders/polynomial.py#L79)
- [sum_coding.py](https://github.com/scikit-learn-contrib/categorical-encoding/blob/3c03f8eba2df26be3e0b15814a1e281dec0b0938/category_encoders/sum_coding.py#L79)
- [one_hot.py](https://github.com/scikit-learn-contrib/categorical-encoding/blob/056a483eff86f1ca1f57d7b7c0fab520fa988200/category_encoders/one_hot.py#L77)
- [ordinal.py](https://github.com/scikit-learn-contrib/categorical-encoding/blob/056a483eff86f1ca1f57d7b7c0fab520fa988200/category_encoders/ordinal.py#L74)

If this is better as a new issue let me know and I'll create it.

**Comment by wdm0006** [comment]
Nope, this issue is fine, I'll update them real quick thanks for the heads up.
