### ISSUE TITLE
Try to use hashencoder but fail due to high memory usage

### ISSUE THREAD

**Issue by stevewyl** [scikit-learn-contrib/categorical-encoding#33]
I tried to convert several categorical columns to hash-encoding features and the size of input data is 2.7 million, one column has 20K category. But the amount of memory will be up to 10G, it's a very strange situation. Why the encoder used so much memory?

**Comment by wdm0006** [comment]
How large in bytes is the dataset being passed in? If it's a pandas dataframe you can use `df.info(memory_usage=True)` to find out. 

Also what are you using for `n_components`?

**Comment by stevewyl** [comment]
The dataset is just 170MB, I set the n_components as 500.

**Comment by wdm0006** [comment]
How many columns are there in the original dataset, and how many of those are being encoded with the HashingEncoder (by default it'd be all).

**Comment by wdm0006** [comment]
Closing this, feel free to re-open if you're still having issues.
