### ISSUE TITLE
Leave One Out Encoding Behavior

### ISSUE THREAD

**Issue by apapiu** [scikit-learn-contrib/categorical-encoding#38]
I've been trying the `LeaveOneOutEncoder` but from what I can tell it just takes the mean of the target given the current levels without leaving the current example out. Also it seems like setting `randomized = True` does not seem to add any noise. Am I missing something?

Doing the example in the docs:

``` python
from category_encoders import *
import pandas as pd
from sklearn.datasets import load_boston
bunch = load_boston()
y = bunch.target
X = pd.DataFrame(bunch.data, columns=bunch.feature_names)

enc = LeaveOneOutEncoder(cols=['CHAS', 'RAD'], randomized = True).fit(X, y)
numeric_dataset = enc.transform(X)
```

Just replaces the `'CHAS'` and  `'RAD'` columns with the mean of the target grouped by the corresponding variable.

I'm using: 
`Python 2.7.13`
`category-encoders==1.2.4`
`pandas==0.20.3`
`numpy==1.13.1`

**Comment by wdm0006** [comment]
Hmmm, thanks for the ticket, I'll take a look.

**Comment by wdm0006** [comment]
Sorry for the delay, it's really just not a great example, we should change it. If the variable being encoded has a category with only one observation then that observation's value is imputed as the mean, like you say. So in this dataset, that happens to be everything. We should switch the example to mushroom dataset or something like that.

**Comment by apapiu** [comment]
Hey thanks for the response - I think I get what you're saying. Also the behavior of just outputting the mean does make sense on _new_ data. 

However for this particular encoder the `.transform` would need to have two different behaviors: 

- on the  original data, the transformed version should have the leave one out and noise included
- on new data it should just output the mean per group(as it does now). 

Hopefully that's not too confusing. I guess my question now is: how do I get the leave one out transformation on the original data if I want to use that to train an ML model.

**Comment by wdm0006** [comment]
I don't think the issue here is on new/old data, it's that it's on not-really-categorical data. There have to be multiple observations with the same value (so think, a column of gender, where you have 1000 rows of either M, F or null), or you will see the behavior described above. 

Leave-one-out, more so than other categorical methods is sensitive to this case.

**Comment by apapiu** [comment]
I see what you mean in terms of not having multiple observations of the same value but the columns in the Boston dataset used in the example do not behave that way - take for example `'RAD'`:

```
>>>X["RAD"].value_counts()
24.0    132
5.0     115
4.0     110
3.0      38
6.0      26
8.0      24
2.0      24
1.0      20
7.0      17
Name: RAD, dtype: int64
```

However the `.transform` will still only return the mean per group.
I've also tried transforming it to an object dtype but the behavior is the same.

So I guess looking back to the image in the original Kaggle forum the documentation references:
![image](http://i.imgur.com/lYZcUny.png)


My question is: how can I use this transformer to get the EXP_UID on the training set as shown there?

**Comment by wdm0006** [comment]
Ah, then I'd guess you are using the default randomized=False, try setting that to True if so.

**Comment by wdm0006** [comment]
Marking this closed, if randomized didn't fix your issue, feel free to reopen.
