### ISSUE TITLE
target encoding

### ISSUE THREAD

**Issue by rspadim** [scikit-learn-contrib/categorical-encoding#40]
should be nice this one too:

https://www.kaggle.com/ogrellier/python-target-encoding-for-categorical-features

**Comment by wdm0006** [comment]
This does look interesting, would you like to help work on a PR for it?

**Comment by chappers** [comment]
There is a link to the actual paper here: https://kaggle2.blob.core.windows.net/forum-message-attachments/225952/7441/high%20cardinality%20categoricals.pdf

**Comment by intern1knowdis** [comment]
@chappers the link does not work :disappointed:

**Comment by janmotl** [comment]
The article is still available from:
	https://dl.acm.org/citation.cfm?id=507538
