### ISSUE TITLE
testing new coding methods

### ISSUE THREAD

**Issue by dribnet** [scikit-learn-contrib/categorical-encoding#41]
Hi - is there a standard metric that's been established to evaluate the performance of the various categorical encoding methods? In my own work I use a generalization of 1-hot encoding I call [k-hot encoding](https://gist.github.com/dribnet/163656a1c57150def7909cbebf4f07d9), where k denotes the number of activate bits. I'd be keen to evaluate it on a standard metric if one exists to see if it's any good for more general tasks.

**Comment by wdm0006** [comment]
Hey,

K-hot sounds somewhat, but not quite, similar to the BaseN encoding we have here. I'd be interested to see how they compare in practice, K-hot may be worth adding into the library to see. 

As for evaluation, there are some heuristics, like total dimensionality (so compression), and distortion (stdev of l2 distance between random points once encoded, should be very low). There is also the option of comparing eventual model performance on a mix of datasets (shown in the examples directory). Formally, I'm not sure of a much better way, but I'd be very interested to find one.

**Comment by wdm0006** [comment]
Moved this into a more specific #46, if you'd like to implement your k-hot algorithm, please open a separate issue for that.
