### ISSUE TITLE
What's the formula for HelmertEncoder

### ISSUE THREAD

**Issue by lihuiknight** [scikit-learn-contrib/categorical-encoding#43]
Could someone tell me the detail processing logic for HelmertEncoder? My Code as below:
sales = [{'account': 'Jones LLC', 'Jan': 150, 'Feb': 200, 'Mar': 140},
         {'account': 'Alpha Co',  'Jan': 200, 'Feb': 210, 'Mar': 215},
         {'account': 'Blue Inc',  'Jan': 50,  'Feb': 90,  'Mar': 95 }]
X = pd.DataFrame(sales)
y = np.array([1, 0, 1])

enc = HelmertEncoder(cols=['account']).fit(X, y)
numeric_dataset = enc.transform(X)
print(numeric_dataset)

Actually, how does HelmertEncoder tansfer [0, 1, 2] to [[1 -1 -1],[1 1 -1],[1 0 2]]?

**Comment by wdm0006** [comment]
Hey,

Thanks for checking out the library, here are some resources for Helmert encoding (we pass through to statsmodels for the actual computation, their "Helmert" is akin to what many would call "Reverse Helmert").

https://stats.idre.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/#HELMERT

http://www.statsmodels.org/dev/contrasts.html
