### ISSUE TITLE
Encode as integers or strings?

### ISSUE THREAD

**Issue by miskolc** [scikit-learn-contrib/categorical-encoding#53]
https://github.com/scikit-learn-contrib/categorical-encoding/blob/d165a4957a7f4a8ca0287d8c01d44be6cf21aa3c/category_encoders/binary.py#L228

I was reading the code to understand how the algorithm works and I noticed you the `col` array contains arrays and the list of zeros you prepend to it contains integers. I think the data type used should be consistent, either use integers or strings.

**Comment by wdm0006** [comment]
Totally agree, I think both should be integers. Would you like to work on a PR for this fix?
