### ISSUE TITLE
OneHotEncoder creates dummy column

### ISSUE THREAD

**Issue by andrethrill** [scikit-learn-contrib/categorical-encoding#54]
In the following example:

```
>>> myDf = pd.DataFrame({'col': ['a', 'b', np.NAN]})
>>> enc = ce.OneHotEncoder(cols=['col'])
>>> enc = enc.fit(myDf)
>>> enc.transform(myDf)
  col_0  col_1  col_2  col_-1
0      1      0      0       0
1      0      1      0       0
2      0      0      0       1
```

I believe `col_2` should not be created. I think this is a bug created due to `OneHotEncoder` calling internally `OrdinalEncoder` and both are imputing an extra category.

Happy to hear if I am wrong?

**Comment by wdm0006** [comment]
Yes, this appears to be the same bug as #52, NaN and None are treated badly, so we get them as both a new category (which never appears), and then get an unknown column (the -1 col here). 

I'm going to open an issue for this bug and close the two issues currently open, if you or @wenwu313 are interested in working on a fix check in over there.
