### ISSUE TITLE
Add weight of evidence encoding

### ISSUE THREAD

**Issue by eyadsibai** [scikit-learn-contrib/categorical-encoding#59]

**Comment by wdm0006** [comment]
Hey Eyad, are you interested in working on a PR for this?

**Comment by eyadsibai** [comment]
Sure!

**Comment by wdm0006** [comment]
Excellent, thanks.

**Comment by JoshuaC3** [comment]
@eyadsibai This sounds great!

For those who are not sure what it is [here](https://www.slideshare.net/0xdata/feature-engineering-83511751) is a nice example of it!

**Comment by eyadsibai** [comment]
I started it. It is not a lot of work. I should resume soon

**Comment by janmotl** [comment]
@eyadsibai, the library now contains WOEEncoder. Can you check the newest code before it gets into the release? 

The implementation is based on LeaveOneOutEncoder. And it implements regularization via Laplace correction. To my disappointment, the performance of WoE appears to be in all respects (runtime, training and testing accuracy) comparable to LeaveOneOutEncoder even if evaluated with logistic regression (see [plots](https://github.com/scikit-learn-contrib/categorical-encoding/tree/master/examples/benchmarking_large/output)). I will be glad if you find bugs.
