### ISSUE TITLE
[Question] Can i get transformed names from encoders? 

### ISSUE THREAD

**Issue by sharthZ** [scikit-learn-contrib/categorical-encoding#63]
When i use encoders in `FeatureUnion` after `transform` i always get `numpy.ndarray` regardless of what was fed to the input, `pd.DataFrame` or smth else. When i try get new feature names by `FeatureUnion.get_feature_names()` i got `AttributeError: Transformer ohe (type OneHotEncoder) does not provide get_feature_names.`. So how can i know transformed feature names?

**Comment by wdm0006** [comment]
you can pass return_df=True to the constructor to get a dataframe out instead of a numpy array.
