### ISSUE TITLE
Target Encoding for regression task?

### ISSUE THREAD

**Issue by mrgloom** [scikit-learn-contrib/categorical-encoding#68]
Is it possible to use Target Encoding for regression task?

**Comment by wdm0006** [comment]
Hmm, it might run, but I'm not sure that it will give you results that work out as you'd like. Worth a shot, if it does work it's not intentional but comment back here, it'd be cool.

**Comment by mrgloom** [comment]
Looks like it works without throwing exception, but quality is less then my naive way of mean encoding even without k-fold, smoothing, etc.
