### ISSUE TITLE
Issue at install with statsmodels v 0.9.0

### ISSUE THREAD

**Issue by hayesgb** [scikit-learn-contrib/categorical-encoding#69]
I encountered an issue with categorical-encoders and a new release of statsmodels.  I've created a package, and when calling `pip install .` on the package to install it in a Docker container, I get the following:

```
  Downloading https://files.pythonhosted.org/packages/67/68/eb3ec6ab61f97216c257edddb853cc174cd76ea44b365cf4adaedcd44482/statsmodels-0.9.0.tar.gz (12.7MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-e8na0ezb/statsmodels/setup.py", line 347, in <module>
        from numpy.distutils.misc_util import get_info
    ImportError: No module named 'numpy'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-e8na0ezb/statsmodels/
The command '/bin/sh -c pip install .' returned a non-zero code: 1
```

This worked prior to the release of statsmodels 0.9.0, which was released at the end of April 2018. 
 Specifying statsmodels==0.8.0 in the setup.py  `install_requires` list eliminated the issue.

**Comment by wdm0006** [comment]
Hmmm, this is strange. We might should pin the req at 0.8.0 here and bring it up to the statsmodels folks?
