### ISSUE TITLE
Request to add support for pandas categorical types when using OrdinalEncoder

### ISSUE THREAD

**Issue by dennisobrien** [scikit-learn-contrib/categorical-encoding#70]
Hi All,

I ran into an issue using OrdinalEncoder where I assumed that it would use the mapping in the categorical types in the passed pandas dataframe.  Instead, it created a mapping based on the order of the data passed to `fit_transform`.  I realize that this is user error, but it would be nice for OrdinalEncoder to use the existing mapping information from the categorical dtype.  If the maintainers think this would be a nice addition, I'd be happy to make a PR.

Here's a demonstration of the issue.

First I'll create a categorical dtype and a dataframe that uses it.
```python
from category_encoders.ordinal import OrdinalEncoder
import pandas as pd
from pandas.api.types import CategoricalDtype

platforms = ['android', 'ios', 'amazon']
platform_category = CategoricalDtype(categories=platforms, ordered=False)

df = pd.DataFrame([
    {'id': 1, 'platform': 'android'},
    {'id': 2, 'platform': 'ios'},
    {'id': 3, 'platform': 'amazon'},
])
df['platform'] = df['platform'].astype(platform_category)
print(df)
```
```
   id platform
0   1  android
1   2      ios
2   3   amazon
```

The encoding from the categorical dtype looks like this:
```python
[(cat, code) for code, cat in enumerate(df['platform'].cat.categories)]
```
```
[('android', 0), ('ios', 1), ('amazon', 2)]
```

Now I'll make an encoder without a mapping parameter, then transform with the data sorted.
```python
cat_encoder_a = OrdinalEncoder(cols=categorical_columns)
df_a = cat_encoder_a.fit_transform(df.sort_values(by='platform', ascending=True))
print(df_a)
```
```
   id  platform
0   1         0
1   2         1
2   3         2
```

The category mapping from the encoder happens to match the categorical dtype mapping because of the sort order of the dataframe.
```python
cat_encoder_a.category_mapping
```
```
[{'col': 'platform', 'mapping': [('android', 0), ('ios', 1), ('amazon', 2)]}]
```

But if I reverse the order of the data passed to `fit_transform` I will get a different mapping.
```python
cat_encoder_b = OrdinalEncoder(cols=categorical_columns)
df_b = cat_encoder_b.fit_transform(df.sort_values(by='platform', ascending=False))
cat_encoder_b.category_mapping
```
```
[{'col': 'platform', 'mapping': [('amazon', 0), ('ios', 1), ('android', 2)]}]
```

I can get a stable mapping from the categorical types in the dataframe itself (instead of relying on the order of the data).
```python
category_mapping = [
    {'col': column_name, 'mapping': [(cat, code) for code, cat in enumerate(df[column_name].cat.categories)]} 
    for column_name in df.select_dtypes(['category']).columns
]
category_mapping
```
```
[{'col': 'platform', 'mapping': [('android', 0), ('ios', 1), ('amazon', 2)]}]
```

```python
cat_encoder_c = OrdinalEncoder(cols=categorical_columns, mapping=category_mapping)
df_c = cat_encoder_c.fit_transform(df).sort_values(by='platform', ascending=False)
cat_encoder_c.category_mapping
```
```
[{'col': 'platform', 'mapping': [('android', 0), ('ios', 1), ('amazon', 2)]}]
```

So while it is not hard to pass a custom mapping, it would be nice for `OrdinalEncoder` to handle this automatically if no `mapping` is passed __and__ if any of the columns are pandas categoricals.  I think this logic could be handled around here.  https://github.com/scikit-learn-contrib/categorical-encoding/blob/1.2.6/category_encoders/ordinal.py#L270

If others think this would be a positive addition, I will make a PR.

thanks,
Dennis

EDIT: I modified the above code to fix a bug in getting the mapping from the pandas categorical dtype.  The previous code I had happened to work only because the data was in order, but in general that does not work.  The correct way is
```python
[(cat, code) for code, cat in enumerate(df[column_name].cat.categories)]
```

**Comment by wdm0006** [comment]
This makes a lot of sense, and I think would be a great addition. I look forward to a PR, if you run into trouble let me know.
