### ISSUE TITLE
New version request

### ISSUE THREAD

**Issue by kuraga** [scikit-learn-contrib/categorical-encoding#73]
Good day!

There are some bugfixes and `use_cat_names` new feature. What about a new version?

**Comment by wdm0006** [comment]
Hey @kuraga, good point. I'll take a look at what all is open, we have a few contributors who are working on PRs right now, but if they're not soon-to-be-done we can go ahead and cut a release with whats already been merged.

**Comment by wdm0006** [comment]
@kuraga https://pypi.org/project/category_encoders/ release cut
