### ISSUE TITLE
How to deploy Hashing Encoder?

### ISSUE THREAD

**Issue by andymancodes** [scikit-learn-contrib/categorical-encoding#75]
Hi,

I used Hashing encoder for my model. 

The problem is now I want to deploy my model.

How will I encode my values at prediction time?

The Hashing encoder has only hash_method attribute but no mapping attribute.

Please help.

**Comment by wdm0006** [comment]
I'd recommend serializing the trained encoder with joblib, loading it at prediction time, and calling transform(). 

There is no mapping for a hashing encoder.

**Comment by andymancodes** [comment]
@wdm0006 thanks, are the encodings trained? What is the training procedure? I saw md5 as the  I though encodings like binary establish arbitrary mappings to categorical inputs.. could you elaborate or point me to a resource where this training is explained..

**Comment by andymancodes** [comment]
@wdm0006 also, can't I pickle the encoder and use it?

**Comment by wdm0006** [comment]
The encodings are trained differently depending on the encoder. For hashing trick, in general, it's a just a hash, so there is nothing to learn. This runs in transform: https://github.com/scikit-learn-contrib/categorical-encoding/blob/master/category_encoders/hashing.py#L161, you can specify different hashing methods, like MD5. 

The methodology is also explained well here: https://en.wikipedia.org/wiki/Feature_hashing

Pickle may work but I'd recommend joblib. Scikit-learn has good documentation on how to serialize estimators and transformers, which I'll defer to here.
