### ISSUE TITLE
How to choose an encoding method?

### ISSUE THREAD

**Issue by andymancodes** [scikit-learn-contrib/categorical-encoding#76]
Hi, 

I am not getting any resources on what encoding to choose for my model.

I tried Binary and Hashing encoding but the predictions are way worse using the Binary encoding.

How to choose an encoding that is suited for my problem?

Any help is greatly appreciated. Thanks!!

**Comment by wdm0006** [comment]
For now transformer selection is outside of scope of this project. Scikit-learn itself has model and pipeline selection tooling. The most straightforward approach would be something like a grid search.

**Comment by wdm0006** [comment]
also please note that v1.2.7 had a critical bug in hashing encoder, if you were using that, try with v1.2.8

**Comment by andymancodes** [comment]
@wdm0006 thanks for the reply, i am trying different values but the hashing encoder just return the same values with very different variables..
