### ISSUE TITLE
Add get_feature_names() method

### ISSUE THREAD

**Issue by eyadsibai** [scikit-learn-contrib/categorical-encoding#79]
Many transformers in sklearn has the get_feature_names() method which is essential to use with FeatureUnion class. They are adding the method to the rest of the transformers
https://github.com/scikit-learn/scikit-learn/issues/6425
https://github.com/scikit-learn/scikit-learn/pull/10198
https://github.com/scikit-learn/scikit-learn/pull/6445
https://github.com/scikit-learn/scikit-learn/pull/6441

I would say it is important to have that method in the transformers of this package. In this way, we can use is with FeatureUnion and get the feature names in a nice way plus being compatible with scikit-learn

**Comment by wdm0006** [comment]
Hey @eyadsibai, agreed.  Are you interested in working on this? I think similar to how they've gone about it up in sklearn, we ought to as a group get one transformer implemented in a clear way, then can make other issues for adding similar support to the remaining ones.

**Comment by eyadsibai** [comment]
@babaktr

**Comment by janmotl** [comment]
Solved in #141
