### ISSUE TITLE
which of the encoders work for classification and which work for regression

### ISSUE THREAD

**Issue by sebastiangonsal** [scikit-learn-contrib/categorical-encoding#82]
I think TargetEncoder throws some errors with regression?

**Comment by wdm0006** [comment]
Target encoder I believe is specific to classification, as is leave one out. The remaining encoders should at least run, but may not be effective.  We should probably add a table specifying compatibility to the README or docs though, this has come up a few times.

**Comment by sebastiangonsal** [comment]
I think in target for regression, we should be taking average of the label? while in case of classification  we are going to take the ratio. Are you doing that in the code? Can you point me to the code where you are doing the actual work.
