### ISSUE TITLE
Save training encoder value and use it in testing

### ISSUE THREAD

**Issue by kc004** [scikit-learn-contrib/categorical-encoding#87]
I am facing a problem with loading same encoding values in testing.

I encoded value using below code (Training side):
`from sklearn.preprocessing import LabelEncoder
    labelencoder_x_0 = LabelEncoder()
    labelencoder_x_0.fit(x[:, 0]) 
    x[:, 0] = labelencoder_x_0.transform(x[:, 0])` 
also tried with .fit_transform()

On the Testing side I loaded model and tried to use the same encoding using below code:
`labelencoder_x_0 = LabelEncoder()
      x[:, 0] = labelencoder_x_0.transform(x[:, 0])`

**ERROR**: sklearn.exceptions.NotFittedError: This LabelEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

I did save my model using this code:
`with open("model.json", "w") as json_file:
        json_file.write(model_json)
 fit1.save_weights("model.h5")`

and load the model using below code:
`json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
 json_file.close()
model = model_from_json(loaded_model_json)
model.load_weights("model.h5")`

How to use same encoding values as training in the testing?

**Comment by wdm0006** [comment]
Label encoder is not from this project, please open this as an issue on sklearn's project.
