### ISSUE TITLE
Compatibility with pandas<0.21.0 in binary.py

### ISSUE THREAD

**Issue by janmotl** [scikit-learn-contrib/categorical-encoding#88]
I got an error:

```
File "/categorical-encoding/category_encoders/binary.py", line 261, in binary
    X_unique, how='left', left_on=col, right_index=True).drop(columns=[col]))
TypeError: drop() got an unexpected keyword argument 'columns'
```

After looking at the documentation https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.drop.html the issue was evident: `DataFrame.drop is using syntax introduced in pandas 0.21.0` but I was running pandas 0.20.1.

Nevertheless, that should have been ok as `requirements.txt` contains `pandas>=0.16.0`.

A possible solution to the issue is to change the following substring `.drop(columns=[col])` into `.drop(labels=col, axis=1)`, which is compatible with both, old and new versions of pandas.

**Comment by wdm0006** [comment]
That's a good point. Would you like to work on a PR for this?
