### ISSUE TITLE
Reverse_dummies() does not work well with undescrores in column names or values

### ISSUE THREAD

**Issue by janmotl** [scikit-learn-contrib/categorical-encoding#96]
Reverse_dummies() in OneHotEncoder does not produce correct results when an original column name contains an underscore. OneHotEncoder adds an underscore before the attribute name (e.g.: `'attribute_name'`) and its value. But then we may get something like `col0 = 'attribute_name_13'` and the following code:
```
col0.split('_')[1]
```
selects the second token `'name'` instead of the last token `'13'`. A possible fix is to use:
```
col0.split('_')[-1]
```

However, if we use `use_cat_names=True`, we have to be careful about underscores among the values, because the encoded column names may look like `attribute_name_value_name` and it is not enough to select the last token. A possible solution is to simply remove the known prefix with something like:
```
col0[prefix_length:]
```
and in the calculation of `val`:
```
val = tran_col[prefix_length:]
```

Where `prefix_length` is precalculated in front of the loops:
```
prefix_length = len(col)+1  # Original column name plus underscore
```

It solves the problem and it should be even faster than than the current solution as we directly select the substring without the need to repeatedly traverse the strings char by char to find the separators, as is happening in `split()` function.

**Comment by janmotl** [comment]
The same issue appears in BaseNEncoder class in basen_to_interger function.

**Comment by wdm0006** [comment]
Thats interesting, would you like to work on a PR for this?  Sounds like a good solution.
