### ISSUE TITLE
BaseN encoder should fillna only in generated columns 

### ISSUE THREAD

**Issue by janmotl** [scikit-learn-contrib/categorical-encoding#97]
Currently, BaseN encoder replaces NA/NaN values in the whole DataFrame:
```
X.fillna(0.0, inplace=True)
```
However, I do not think that is desirable - categorical encoder should touch only columns that are (explicitly or implicitly) specified in `cols` parameter. The remaining columns should be left untouched.

A possible (although ugly) solution:
```
        original_cols = set(X.columns)
        # ... Encoding of X...
        current_cols = set(X.columns)
        # Apply only on newly generated columns: 
        #   on all current columns - (all original columns - encoded columns)
        fillna_cols = current_cols - (original_cols - set(self.cols))
        for col in fillna_cols:
            X[col].fillna(0.0, inplace=True)
```

**Comment by wdm0006** [comment]
Agree with the premise here, but you can do it without a for-loop:

`df[['a', 'b']] = df[['a','b']].fillna(value=0.0)`

Not sure if that's better or worse than  the inplace version though.

**Comment by janmotl** [comment]
`X[fillna_cols] = X[fillna_cols].fillna(value=0.0)` is significantly faster than the loop.

**Comment by wdm0006** [comment]
Great, are you interested in working on a PR for this change?
